### ISSUE TITLE
[QUESTION] 오전에는 예약이 되었었는데 다시하니까 한병원만 나오고 신청이 선착순 마감되었다고 나옵니다

### ISSUE THREAD

**Issue by juliajy** [SJang1/korea-covid-19-remaining-vaccine-macro#1005]
오늘 9일이라 생일이 9일자라 신청했는데 9월중순 접수로 떠서 
깃허브에서 돌렸는데 예약이 되었는데 이미 신청한사람이라고 뜨는게 있었어요 
그래서 홈페이지가서 백신예약 취소하고 다시 메크로 돌렸더니 
한개병원만나오고 잔여백신 접종 신청이 선착순 마감되었습니다고 뜹니다 
어떻게 해결해야되나요?
![11](https://user-images.githubusercontent.com/88690242/128803482-799f6251-caa1-4ecb-aeb7-041b7d6336de.PNG)

**Comment by ssvaccine** [comment]
현재 az때매 매크로 이용을 자제중이라고 공지사항 쓰신 게 있는 것 같네요. 오늘 정기신청 날이시라면, 신청해두시는 게..

**Comment by SJang1** [comment]
공지사항에 적어두었습니다만, 잔여백신을 맞겠다고 기존 예약을 취소하는 일은 없도록 해주세요..

> 이미 백신을 예약한 사람은 잔여백신 예약을 할 수 없습니다. 잔여백신 경쟁에 뛰어들겠다고 기존 예약을 취소하는 일은 없도록 기존 일정에 맞게 백신을 맞아주세요.

또한, 현재 일시적으로 이용 중단을 권고한 상태입니다 : https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/discussions/962

해당 문제 해결 후 다시 이용을 시작해주세요 : #972 #979
