### ISSUE TITLE
[BUG] 크롬브라우져로 접속하니 지원하지 않는 환경이라고 뜹니다.

### ISSUE THREAD

**Issue by JihyeJung-Work** [SJang1/korea-covid-19-remaining-vaccine-macro#1055]
크롬브라우저로 카카오로그인을 하고 병원들을 클릭하면 지원하지 않는 환경이라고 뜹니다.
막힌건가요?

**Comment by clianor** [comment]
저도 동일합니다

**Comment by clianor** [comment]
@Queue-ri 클릭뿐 아니라 화면전환 및 모든 상황에서 발생합니다.

**Comment by Queue-ri** [comment]
@clianor 일단 이슈가 Closed 되었으므로 추가 질문은 Discussions에 올려주시기 바랍니다.
