### ISSUE TITLE
좌표를 어떻게 입력해야하나요?

### ISSUE THREAD

**Issue by mukoon** [SJang1/korea-covid-19-remaining-vaccine-macro#1082]
사각형의 왼쪽 위 경위도를 넣어주세요. 37.28631662121671, 126.81741443463375: 이렇게 뜨는데 제좌표가 37.27604266597629, 127.10563636718554 인데 그냥 이렇게 복사 붙여넣기하면 되는건가요 아니면 순서가 있나요 ? 저걸그대로 입력하면 사각형의 오른쪽아래 경위도를 넣어주세요 라고 떠가지구요 이게 맞는건지 여쭤봅니답 두번다 제 좌표를 입력하는게 맞는건가여?

**Comment by SJang1** [comment]
지금 입력하신 대로 복사 붙여넣기 하시면 됩니다. 올바른 순서로 입력하시려 하시고 계셨습니다.
두번 다 각각 위치에 맞는 좌표를 넣으시면 됩니다.
