### ISSUE TITLE
개발자님 새로운버전 실행이안되요. 도와주세요[기존꺼는 돌아가요]

### ISSUE THREAD

**Issue by dukyoung58** [SJang1/korea-covid-19-remaining-vaccine-macro#109]
![캡처](https://user-images.githubusercontent.com/87853631/126918909-348842b6-ae88-4396-8c1b-e2f5d3faee7f.PNG)

**Comment by SJang1** [comment]
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/issues/82
