### ISSUE TITLE
Failed to find Chrome cookie

### ISSUE THREAD

**Issue by zuge3927** [SJang1/korea-covid-19-remaining-vaccine-macro#119]
window에서 1.0.6 이후의 버전 vaccine.exe 실행할경우 바로 exe(커맨드)창이 종료됩니다.

**Comment by SJang1** [comment]
오류로그를 알 수 있을까요?
cmd를 여시고 해당 cmd창 안에서 exe를 실행하시면 로그 유지된 채로 볼 수 있습니다.

**Comment by zuge3927** [comment]
C:\Users\Administrator>cd desktop

C:\Users\Administrator\Desktop>cd vaccine

C:\Users\Administrator\Desktop\vaccine>cd vaccine-run-kakao-windows

C:\Users\Administrator\Desktop\vaccine\vaccine-run-kakao-windows>start vaccine-run-kakao.exe

이렇게 실행하면 똑같이 다른 exe 커맨드창이 잠깐 떳다가 바로 꺼집니다.

**Comment by dlddnd** [comment]
@zuge3927 혹시 윈도우 버전이 어떻게 되시나요?? 윈도우7이면 안될 수도 있어요

**Comment by SJang1** [comment]
`start vaccine-run-kakao.exe` 말고 그냥 `vaccine-run-kakao.exe`로 실행해 보세요.

**Comment by zuge3927** [comment]
그냥 vaccine-run-kakao.exe 실행하니까 

C:\Users\Administrator\Desktop\vaccine\vaccine-run-kakao-windows>vaccine-run-kakao.exe
pygame 2.0.1 (SDL 2.0.14, Python 3.9.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "vaccine-run-kakao.py", line 24, in <module>
  File "browser_cookie3\__init__.py", line 596, in chrome
  File "browser_cookie3\__init__.py", line 383, in __init__
  File "browser_cookie3\__init__.py", line 192, in __init__
  File "browser_cookie3\__init__.py", line 249, in __add_key_and_cookie_file
browser_cookie3.BrowserCookieError: Failed to find Chrome cookie
[78936] Failed to execute script 'vaccine-run-kakao' due to unhandled exception!

이렇게 뜹니다

**Comment by SJang1** [comment]
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/issues/82
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/issues/82#issuecomment-886197186
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/discussions/123#discussioncomment-1048708

**Comment by zuge3927** [comment]
크롬을 지우고 새로 설치했는데 default라는 폴더는 안보입니다.

**Comment by SJang1** [comment]
크롬을 지우고 
C:\Users\USER\AppData\Local\Google 폴더도 지우고
다시 설치해보세요.

**Comment by zuge3927** [comment]
아 google폴더까지 지우고 새로 설치하니까 됩니다!
감사합니다
