### ISSUE TITLE
사각형 좌표지정 문제입니다.

### ISSUE THREAD

**Issue by soosooho** [SJang1/korea-covid-19-remaining-vaccine-macro#18]
백신 코드 입력 후 사각형 좌측 위 127.xxxxxx 가 고양시 일산 기준 구글 좌표를 찍으면 126.~~~~ 로 나오기때문에 입력 할수가 없는데 어떻게 해야 될까요?

**Comment by SJang1** [comment]
그대로 126.~~~로 입력하시면 됩니다. 127은 예시입니다.

**Comment by soosooho** [comment]
> 그대로 126.~~~로 입력하시면 됩니다. 127은 예시입니다.

아하 감사합니다. 이런 프로그램은 처음 써봐서요 ㅎㅎ 위에 x값만 집어넣을 수 있는줄 알았습니다.!!
