### ISSUE TITLE
파이썬에서 찾았다고뜨는데 예약되지 않았습니다. 알 수 없는 페이지

### ISSUE THREAD

**Issue by salvare070** [SJang1/korea-covid-19-remaining-vaccine-macro#19]
![Screenshot_20210723-154021_Remote Desktop](https://user-images.githubusercontent.com/76022283/126746113-aefbcf14-b8dd-47ea-bd9d-57217df6565c.jpg)
안녕하세요! 말씀해주신대로 파이참(3.8)에서 실행해서 정상 작동 시키는 도중 밑에 터미널에서 찾았다고 떳지만 크롬 페이지에서는 '알 수 없는 페이지'라 뜨고 예약도 안됬습니다. 카카오도 로그인 했는데, 실패문구와 성공문구가 터미널에 따로 구분은 없을까요? 또 제가 어떤 점을 잘못했는지 지적 부탁드려도 될까요?
휴대폰으로 원격으로보면서 작성해서 사진이나 문장이 이상할 수 있습니다!
읽어주셔서 감사합니다.

**Comment by SJang1** [comment]
> https://vaccine.kakao.com/api/v1/user 에 접근하여 본인의 정보가 정상적으로 표시되는지 확인합니다.
> 정상적으로 표시되지 않는 경우 카카오톡에서 잔여백신 알림 신청을 해줍니다.

이 부분을 안 하신 것 아닐까 싶습니다.
잔여백신 신청 전에 미리 정보제공 등 동의를 해두셔야 예약이 진행이 될 수 있습니다. 해당 부분 동의가 잔여백신 알림 신청으로 가능합니다.

예약은 순전히 브라우저가 담당하므로 터미널이 알 길이 없습니다.

**Comment by salvare070** [comment]
그 부분도 정상적으로 뜨는 것을 전부 확인했었는데 이상하네요.. 내일이나 월요일에 말씀하신거 한번 더 꼭 체크하고 다시 해봐야겠네요. 빠른 답변 감사합니다 ㅎㅎ

**Comment by salvare070** [comment]
주말때 쉬시는데 죄송합니다! 너무 귀찮게 해드려 죄송합니다 ㅠ
추가로 질문 드릴게 있는데 프로그램 오류일지 몰라서 여기에 다시 질문 드립니다.
저는 혹시나 몰라서 설명에 나와있는 링크3개 창 전부 띄워놓고 프로그램을 돌리고 있습니다.
9시부터 프로그램 3개로 진행중인데 현재 4개째 예약 실패라고 뜹니다. 
그런데 바로 예약 실패라고 뜨는것이 아니라, 카카오 오류페이지가 0.5~1초 정도 창이 띄워지다가 예약실패 칸으로 넘어가네요.
인터넷은 크롬을 사용중이며 파이썬, exe 파일 실행 시 둘다 오류 문구 없습니다.
실패할 때는 원래 이렇게 뜨는걸까요?
+지도 범위를 너무 넓게 잡으면 성공확률이 떨어지는지 궁금합니다!

**Comment by SJang1** [comment]
> 실패할 때는 원래 이렇게 뜨는걸까요?

그렇지는 않은데 카카오 서버에서 reservation 요청을 보내기 전에는 오류 페이지가 잠시 표시될 수 있는 것으로 코드상 보입니다.
아무래도 인터넷 환경이 안 좋은 환경에서 그런 상황이 더욱 일어날 수 있으니 인터넷 확인해보시고, 결국 예약실패가 뜬다면 예약시도는 정상적으로 이루어지고 있는 것으로 보입니다.

**Comment by SJang1** [comment]
예약방식 변경으로 이 이슈는 Close하겠습니다.
