### ISSUE TITLE
과도한 사용 시 IP 밴 및 카톡 계정 정지 이슈 있습니다.

### ISSUE THREAD

**Issue by travisseon** [SJang1/korea-covid-19-remaining-vaccine-macro#204]
과도하게 사용될 경우 카톡계정 정지 됩니다.
여러분들 조심하게 하세요.
카톡 계정 정지되는 순간 그 번호로 계정이 완전 정지 되며,
대화 및 오픈톡 채팅방 기능 등 모두 이용 할 수 없습니다.
두려우신분들은 창을 1개만 시키든 사용을 하지 않는 것 을 추천드립니다.....
전 정지 당했구요. 카카오에 전화 많이 해봤는데 기달려라 확인하고 알려주겠다 이말 밖에 안하는 상태입니다
죽겠어요

![image](https://user-images.githubusercontent.com/88009872/127074363-ec42b58f-3df0-4a32-9b5b-4108e12ae857.png)
![image](https://user-images.githubusercontent.com/88009872/127074425-cd150c3d-3b35-4a68-98cf-f603c051f8a6.png)

**Comment by SJang1** [comment]
카카오계정 정보를 사용하는 부분은 병원 내 잔여백신 확인(`ANY`를 선택한 경우에만) 및 실제 예약을 진행할 때 외에는 없습니다.

본인이 다른 문제로 블락당한건 아닌지 잘 생각해보세요.

**Comment by travisseon** [comment]
> 카카오계정 정보를 사용하는 부분은 병원 내 잔여백신 확인(`ANY`를 선택한 경우에만 잔여 병원당 한번) 및 실제 예약을 진행할 때 외에는 없습니다.
> 
> 본인이 다른 문제로 블락당한건 아닌지 잘 생각해보세요.

다른문제로 밴 당한거 아닙니다, ,카카오 전화에서 물어봤어요 다른 사유는 아니랍니다,, 정지는 풀어 줄수 있을지모르겠대요
전 cmd 10개 넘게 틀어서 사용했구요. 기존에는 예약 실패하면 한번에 창이 10개 열리면서 동시에 예약실패가 났던 적이 여러번 있습니다.
그리고 새로 올린버전 사용중에 정지 당했구요 이때도 10개정도 켰습니다.

**Comment by SJang1** [comment]
실제 백신 발생 후 예약진행이 너무 과도하게 되셨네요. 이런 경우는 충분히 블락당할 수 있는 사유..긴 하죠.

제가 괜히 새로 올린 버전에서 여러개 실행하라는 문구를 뺀게 아닙니다. 하나로도 충분합니다.

예약시도를 한 프로그램당 5번 시도하게 되어있었는데 지금은 3번으로 줄인 상태입니다
5*10 = 한 병원 잔여 발생시마다 50번 예약시도를 하게 되는거니까 확실히 저라도 정지시키겠습니다...
안내에 하나만 키라고 단단히 일러놓긴 해야하겠네요.

**Comment by dlddnd** [comment]
와 예약만이 아니라 대화기능까지 차단시키다니 너무한데요

**Comment by dlddnd** [comment]
@travisseon 카카오측에서 제대로 된 답변이 오면 상황 공유해주실 수 있나요?
