### ISSUE TITLE
403 error issue

### ISSUE THREAD

**Issue by ssvaccine** [SJang1/korea-covid-19-remaining-vaccine-macro#205]
안녕하세요.
어제 아침부터 잔여발생은 하는데 예약진행이 안되어 try_reservation request의 리턴을 보니 Response 403이 리턴되고 있더라구요. 정상적인 리턴인가요? 혹은 잔여백신은 계속 찾아지나, 시도하는 부분에서 에러가 나는건가요?
![캡처](https://user-images.githubusercontent.com/88010294/127075397-0fb85f41-3b4e-43e3-853d-864b66982656.JPG)

**Comment by SJang1** [comment]
잔여백신 접종 신청이 마감된 경우 에러코드 403이 정상입니다.
