### ISSUE TITLE
연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다.

### ISSUE THREAD

**Issue by DD8787** [SJang1/korea-covid-19-remaining-vaccine-macro#210]
![error](https://user-images.githubusercontent.com/88011628/127079146-a002123e-002e-409f-a525-a52c79fa1efb.jpg)

40~50분, 짧게는 20~30분마다 위와 같은 화면 잠깐 노출되며 바로 꺼집니다
잠시 7~10초 정도 화면 멈춘 상태로 있다가 순간적으로, 아주 잠깐 노출되는 메시지여서 열심히 캡처했습니다 ㅋㅋㅋㅋ
바로 다시 켜고 있기는 하지만... 사유나 해결 방안을 알 수 있을까요? 최신 버전 사용 중입니다

**Comment by SJang1** [comment]
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/issues/84
