### ISSUE TITLE
한명성공하고 다른카카오톡 아이디로 사용시

### ISSUE THREAD

**Issue by bararak** [SJang1/korea-covid-19-remaining-vaccine-macro#218]
다른분 예약을 하려고하는데 카카오톡을 다른아이디로 로그인을해서 프로그램을 실행하면
기존껄로 계속하겠냐고해서 (N)누르고 시도를하면 중간에 멈춰버립니다.
제가 생각하기에는 기존 아이디로 계속 시도가 되는것같아요
프로그램을 다시 지웠다가 깔아도 그전내용이 안지워지나봅니다
처음부터 사용하려면 어떤걸 지워야 하나요?

**Comment by SJang1** [comment]
프로그램을 실행할 때, 이미 예약된 사람이 시도 시 아예 시도가 안되게 되어 있습니다.
중간에 멈출때 나오는 오류가 있으면 오류를 알려주세요.

**Comment by bararak** [comment]
오류창은 따로안뜨고 시간이 안바뀌고 그냥멈춰있습니다.

**Comment by bararak** [comment]
5분정도 찾다가 더이상 안찾아요

**Comment by SJang1** [comment]
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/issues/84

**Comment by bararak** [comment]
![1](https://user-images.githubusercontent.com/88013365/127084606-5c191bf6-c60c-4fe1-a8e3-85dbf26cf7ef.jpg)

알려주신건 오류창이뜨는데 저는 그냥 아무것도 안뜹니다.
