### ISSUE TITLE
예약성공은 했는데 이전 버전과 달리 오류가 뜹니다

### ISSUE THREAD

**Issue by koala413** [SJang1/korea-covid-19-remaining-vaccine-macro#224]
오전에 백신 3개 떠서 예약은 성공했습니다

근데 이전 버전에서는 「백신접종신청 성공!!!」 메세지 출력후 마지막줄에 "Press Enter to close..." 메세지가 출력됐었는데 테스트 버전은 "Press Enter to close..." 메세지 대신 아래 오류가 뜹니다

제가 사용한 버전은 Actions 탭 중에서 아래 버전을 사용했습니다
Update requirements.txt
Python package #49: Commit 777f170 pushed by SJang1

![캡처2](https://user-images.githubusercontent.com/87846265/127084369-63b4d571-1feb-483f-adbf-c6b1e0c4755d.JPG)

**Comment by SJang1** [comment]
넹 현재 해당 문제 알고있고 수정 개발중입니다.

**Comment by SJang1** [comment]
수정완료
