### ISSUE TITLE
알 수 없는 이유로 예약이 불가능합니다.

### ISSUE THREAD

**Issue by firstwty** [SJang1/korea-covid-19-remaining-vaccine-macro#227]
예약신청까지는 정상적으로 동작하는 듯 합니다.
한가지 질문이 이쓴데요, '알 수 없는 이유로 예약이 불가능합니다' 라는 메시지는 잔여수량이 다른 사람에 의해 먼저 소진되어서 뜨는걸까요?

**Comment by SJang1** [comment]
아니요, 해당 오류 아래에 있는 내용 `{`로 시작하고 `}`로 끝나는 내용을 알 수 있을까요?

**Comment by firstwty** [comment]
창을 이미 종료하여서 관련 로그가 지워진 상태인데, 혹시 또 발생하면 리포팅드리겠습니다 🙏

**Comment by choi** [comment]
@firstwty 님 혹시 외국국적이실까요? 질병관리청 db에 인적사항 등록 안돼있는 경우에 저런 오류가 뜬 다고 들었습니다.
