### ISSUE TITLE
Issue - 선착순 마감되었습니다

### ISSUE THREAD

**Issue by Joon-June** [SJang1/korea-covid-19-remaining-vaccine-macro#235]
![image](https://user-images.githubusercontent.com/39721282/127091730-61319fc9-0480-4c8d-b845-69bd0de4b0e3.png)
어제, 오늘 약 7시간 가량 매크로를 돌렸는데 전부 예약 실패입니다. 계속해서 선착순 마감되었다고 뜨는데요, 제 주변에 다른 분들은 같은 시간대에 수월하게 약 30분 이내로 예약을 성공하신 상태입니다. Pretty print를 disable하고 보니 같은 병원, 같은 물량이 여러 번 검색되는 경우에도 불구하고 예약을 실패하는 상황입니다. 이런 현상을 겪고 계신 분들이 지인분들 중 몇 명 더 있는데요, 뭔가 유저 정보 관련해서 문제가 있는건지... 잘 모르겠네요. 뭔가 아시는 부분이 있으실까요? 아님 정말로 선착순 마감된걸까요?

**Comment by hiskyholic** [comment]
저도 최근버전으로 어제 오늘 돌리고 있는데 (중구, 용산구부터 성동, 광진, 송파까지 좌표 잡아두었습니다. ) 마감만 보고 있습니다. 수량이 적으면 적을수록 더 빨리 나가는 거 같고, 카카오가 아닌 네이버쪽 수요도 있어 그런 것인지 아니면 무엇때문인지 모르겠긴 합니다

**Comment by sukjong2002** [comment]
백신 종류 다른거 아닐까요? 백신 종류 선택 어떤거로 하셨나요?

**Comment by hiskyholic** [comment]
@sukjong2002 화이자(VEN00013)으로 지정해둔 상태입니다

**Comment by Joon-June** [comment]
VEN00013으로 잘 지정해두었습니다~

**Comment by itstours** [comment]
특정 병원서 예약이 완료되었는데도 지도상에서 '마감'으로 뜨지 않고 숫자가 계속 뜨는 경우 (하지만 예약 시도하면 안되는 경우)가 있는데, 그런 상황이 아닐까 싶습니다. 좌표를 다른 곳으로 지정해서 잘 된다면 서버 문제겠지요.

**Comment by SJang1** [comment]
선택한 백신이 없는 경우 또는 진짜 늦은 경우입니다. 버그가 아닙니다.
