### ISSUE TITLE
PyInstaller 오진 이슈 해결법

### ISSUE THREAD

**Issue by itstours** [SJang1/korea-covid-19-remaining-vaccine-macro#240]
안녕하세요. Discussions에 썼다가 혹시 놓치셨나 싶어서 이슈에 올립니다.

저도 최근에 PyInstaller로 executable 만들었다가 동일한 이슈를 겪었는데, 아래 방법으로 해결하여 혹시나 해서 남겨봅니다.
https://jasmine125.tistory.com/1009

위 링크를 따라 Pyinstaller를 일단 삭제하고, bootloader를 직접 빌드한 뒤 Pyinstaller를 재설치하면 해결되었습니다.

제가 직접 executable 만들어 보니 virustotal에서 딱 하나 빼고 오진 문제가 해결되었습니다.
https://imgur.com/a/jOjgX6a

감사합니다.
정윤 드림.

**Comment by SJang1** [comment]
관련된 방법 안내해 주셔서 감사합니다.
현재 pyinstaller으로 빌드하고 있는 방식이 Github Actions라서 정확히 CI를 어캐 바꾸어야 할지 바꾸게 된다면 좀 대대적인 공사가 될 것 같네요.

일단 이 이슈는 Open해두겠습니다

감사합니다 👍
