### ISSUE TITLE
까만 화면에서 넘어가질 않습니다..

### ISSUE THREAD

**Issue by ThidaKim** [SJang1/korea-covid-19-remaining-vaccine-macro#279]
![Screenshot_20210727-161914_Gallery](https://user-images.githubusercontent.com/88025031/127114114-117ccb11-b85f-4a73-9d4f-e1ff17aad35a.jpg)
검정창에서 대기 후 몇분후에 이런 메시지가 뜨며 강제종료됩니다...
시도해본 해결법은
재부팅, 삭제하고 다시 받기 / cmd로 열기 / 압축 폴더 안에 exe파일 넣고 실행 / 백신 프로그램 종료
어떤 방법으로 다시 시도해보아야 할까요?

**Comment by SJang1** [comment]
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/issues/82
