### ISSUE TITLE
프로그램 막힌것 같습니다

### ISSUE THREAD

**Issue by changdocjjang** [SJang1/korea-covid-19-remaining-vaccine-macro#280]
네이버 매크로도 네이버에서 막던데
휴대폰으로는 지도 잘 검색되나
프로그램 먹통인것으로 봐서 카카오에서
막은것 아닌가 의심됩니다 제작자님

**Comment by ssvaccine** [comment]
멀쩡히 잘 되고 있습니다. 5분전에 예약 잡혔네요.

**Comment by changdocjjang** [comment]
> 멀쩡히 잘 되고 있습니다. 5분전에 예약 잡혔네요.

재부팅, 재다운로드 별짓을 다해봐도 프로그램 작동을 안하는데
5분전에 어떤식으로 잡으신건가요? 맥북이신가요?

**Comment by ssvaccine** [comment]
방금 새로 실행해도 잘되네요. 윈도우 입니다. 단순 인터넷 / 서버 문제이신듯합니다

**Comment by no-name-no-idea** [comment]
속성에서 차단해제랑 백신프로그램에서 제외는 하셨나요?

**Comment by mechaminu** [comment]
윈도우 executable로 이용하니 한 4~5번 polling 후에 멎어버리는 증상이 계속 발생하네요. 직접 python으로 script 실행시키니 발생하지 않습니다.
