### ISSUE TITLE
프로그램이 멈춥니다

### ISSUE THREAD

**Issue by TemeraireEurus** [SJang1/korea-covid-19-remaining-vaccine-macro#281]
![image](https://user-images.githubusercontent.com/86486069/127115869-f6ee8a49-0133-44cf-bddf-bbf12238b566.png)
이렇게 멈추거나 예약시도를 하더라도 10회 쯤 탐색을 반복한 후 상기 이미지와 동일하게 멈춥니다

**Comment by RonMaca** [comment]
저도 동일증상입니다. 지도상에서도 잔여백신 조회가 안뜨네요

**Comment by bso-oo** [comment]
저는 몇번 조회하다가 뜨지 않습니다.

**Comment by mechaminu** [comment]
Windows defender 등 백신에서 실행파일 예외설정해도 동일 증상 발생하는지 확인해주세요

**Comment by RonMaca** [comment]
> Windows defender 등 백신에서 실행파일 예외설정해도 동일 증상 발생하는지 확인해주세요

아비라 사용중이고 예외설정해서 실행하고 있습니다 예외설정 안하면 바이러스 파일로 인식해서 지워버리더라구요

**Comment by TemeraireEurus** [comment]
> Windows defender 등 백신에서 실행파일 예외설정해도 동일 증상 발생하는지 확인해주세요

윈도우즈 디펜더 사용 중이고 실행할 때부터 예외설정 하지 않으면 삭제해버리는지라 예외설정이 강권됩니다. 그 전까지는 잘되다가 오늘 오후부터 잘 안되네요

**Comment by THePhanT00M** [comment]
1.0.14로 하면 6번정도 나오다가 멈추는데 최신 코드로 하면 멈추는 현상은 없는거 같습니다.
시간이 늦어 백신 안나왔지만 프로그램이 계속 병원을 찾기는 합니다.

**Comment by VaccineWinner** [comment]
아마 최신코드로 백신 찾으시면 바로 멈출거에요 😅

**Comment by bso-oo** [comment]
exe 는 그럼 사용안되는건가요?

**Comment by SJang1** [comment]
> exe 는 그럼 사용안되는건가요?

README에 적어두었습니다만...
Actions 탭에서 master(최신코드)를 실행 가능한 파일로 변환한 파일을 받을 수 있습니다. (Artifacts)

**Comment by RonMaca** [comment]
> > exe 는 그럼 사용안되는건가요?
> 
> README에 적어두었습니다만...
> Actions 탭에서 master(최신코드)를 실행 가능한 파일로 변환한 파일을 받을 수 있습니다. (Artifacts)
감사합니다 잘 됩니다!
