### ISSUE TITLE
exe 로하면 다운된다해서 파이썬에서 실행하려는데 ModuleNotFoundError: No module named 'browser_cookie3' 이게 뜹니다

### ISSUE THREAD

**Issue by changdocjjang** [SJang1/korea-covid-19-remaining-vaccine-macro#284]
![image](https://user-images.githubusercontent.com/87104616/127116517-6891b5ef-9974-4b06-bca1-81cbe6a1a7d7.png)
도와주세요ㅠㅠ

**Comment by NullableSafety** [comment]
커멘드 라인에서 `pip install -r requirements.txt` 하세요.

**Comment by changdocjjang** [comment]
> 커멘드 라인에서 `pip install -r requirements.txt` 하세요.

![image](https://user-images.githubusercontent.com/87104616/127119290-251fdbf4-4eea-4daf-9b1d-c537017721a9.png)
제작자님 요렇게 뜹니다
저번 버전은 잘됐는데 업뎃 되고 이러네요 ㅠㅠ

**Comment by NullableSafety** [comment]
`python` 하지말고 그냥 커멘드라인에서 `pip install -r requirements.txt` 하신다음에 `python ./vaccion-run-kakao.py` 하세요.
