### ISSUE TITLE
MS Defender의 여전한 바이러스 오진

### ISSUE THREAD

**Issue by Jayyyy-04** [SJang1/korea-covid-19-remaining-vaccine-macro#303]
dc23e26f57046129d57d7031d0565f4d461d4c23 
해당 Releases 내에 있는 windows 실행 파일 다운 시 Antimalware Service Executable Process에서 CPU사용량 급증하는 문제

I5-9400F Desktop - Chrome, Whale 2개의 브라우저 모두 문제 발현 (WIndows10 Pro 19043)
Ryzen 3500U Laptop - Chrome, Whale 2개의 브라우저 모두 문제 발현 (Windows10 Pro 19041)

**Comment by Jayyyy-04** [comment]
Desktop
맬웨어 방지 클라이언트 버전 : 4.18.2107.4
엔진 버전 : 1.1.18300.4
바이러스 백신 버전 : 1.343.1751.0
맬웨어 방지 버전 : 1.343.1751.0


Laptop
맬웨어 방지 클라이언트 버전 : 4.18.2106.6
엔진 버전 : 1.1.18300.4
바이러스 백신 버전 : 1.343.1753.0
맬웨어 방지 버전 : 1.343.1753.0

**Comment by Jayyyy-04** [comment]
기존 다운로드 완료 되지 않은 채 CPU사용량 급증으로 인한 **Windows 탐색기** 멈춤 현상 겪은 후 수 차례 시도하여 다운로드 완료 
하였으나 Windows에서 여전히 Virus 오진

**Comment by SJang1** [comment]
MS Defender의 오진..이 있네요.
있다가 나중에 오진이라고 Submit하겠습니다.

**Comment by MPThLee** [comment]
보니까 아까 VirusTotal 돌린게 MSDefender쪽에서 timeout이 났네요...

아마 지금 빌드 구조상 매번 bootstrap을 새로 빌드하는 형식이라, 매 빌드마다 오진한 부분이 또 바뀔겁니다. 일단 Bootstrap을 빌드하되 최대한 같은 부트스트랩으로 고정하는 방식을 써야할듯 합니다.
사실 이런 부분을 해결하는 가장 좋은 방법은 코드 서명을 해주는건데, 배보다 배꼽이 크네요...

**Comment by SJang1** [comment]
일단 1.0.17 버전은 멀웨어 아님 확인 판정을 받았습니다.
```
We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"
```

**Comment by SJang1** [comment]
> 보니까 아까 VirusTotal 돌린게 MSDefender쪽에서 timeout이 났었네요...
> 
> 아마 지금 빌드 구조상 매번 bootstrap을 새로 빌드하는 형식이라, 매 빌드마다 오진한 부분이 또 바뀔겁니다. 일단 Bootstrap을 빌드하되 최대한 같은 부트스트랩으로 고정하는 방식을 써야할듯 합니다.
> 사실 이런 부분을 해결하는 가장 좋은 방법은 코드 서명을 해주는건데, 배보다 배꼽이 크네요...

빌드한 부분을 CI단에서 캐싱하면 해결할 수 있..을 것 같기도 한데요.. 윈도우쪽은 아예 안쓰고 있어서 코드서명을 어찌 해야할지도 감도 안오고, 저같은경우는 윈도우쪽은 테스트도 제대로 못하고 있습니다.

그와중 MS Defender의 오진 내용이 또 바뀐거같네요.. 또 올려야겠습니다.. 아..

**Comment by Jayyyy-04** [comment]
그래서 사실 저는 이전부터 bat파일을 만들어서 사용중입니다.
모든 사용자들이 Python이 설치되지는 않았겠지만 설치되어 있다는 가정 하에 bat파일은 꽤 매력적으로 다가옵니다ㅎㅎ 저는 Sublime Text 에디터를 사용하는데도 실행은 cmd로 하는 편이거든요.
금일 시간이 된다면 discussions 탭에 간단하게 bat파일에 대하여 기술하겠습니다. 다른 분들에게도 분명 도움이 될 것 같아서요.

**Comment by MPThLee** [comment]
일단 오탐지는 어쩔수 없는것 같습니다. 자체 부트로더를 쓰면 일부에서는 오탐지가 없어지지만, MSDefender는 기본적으로 잡는게 문제네요.

일단 한번 시도해보고있긴한데, 신기하게도 python/pyinstaller를 x86으로 내리면 다른 백신들에선 오탐지가 늘어나는대신, MSDefender(Microsoft)에서는 문제가 사라집니다.
자체 부트로더, pyinstaller v4.3: https://www.virustotal.com/gui/file/a6fdcb3cab84810ced812655ce290cd401413207e7b37da878ae0be35984c717/detection
기본 부트로더, pyinstaller v4.3:: https://www.virustotal.com/gui/file/0661fa3917fad779c6523bb85ef0937569b3577861fdfea47201cf14f121126c/detection

헛웃음이 나오네요...
다음 버전부터는 그냥 기본 부트로더를 사용하고, 빌드 완료 후에 따로 MS쪽에 보고하는게 더 나을것같습니다.

**Comment by SJang1** [comment]
흐음.. 일단 CI쪽에서 부트로더 빌드하는 부분..은 냅두고 부트로더 빌드하는 부분을 Cache해두게 할 수 있을까요?

오탐지는 어쩔 수 없겠지만 만일 캐시된 것을 안쓰고 새로 빌드하면 오탐지 보고하고, 캐시된 부트로더를 사용하게 되면 오탐지 부분도 어느정도 해결이 되지 않을까 싶네요.

**Comment by MPThLee** [comment]
https://github.com/actions/cache 를 사용하면 가능합니다. 근데 좀 많이 복잡해질것 같네요. 현재보다... 

아니면 부트로더쪽 ci 파일을 하나 만들고, 그쪽 artifacts를 이용해서 빌드하는 방법도 있을듯 합니다. 부트로더는 workflow_dispatch를 이용해서 90일(GHA 파일 만료 기본값)마다 새로 만든다고 가정하고요.

**Comment by SJang1** [comment]
> 아니면 부트로더쪽 ci 파일을 하나 만들고, 그쪽 artifacts를 이용해서 빌드하는 방법도 있을듯 합니다. 부트로더는 workflow_dispatch를 이용해서 90일(GHA 파일 만료 기본값)마다 새로 만든다고 가정하고요.

그거 나쁘지 않을것같네요. 어찌해야할지 잘 모르겠어서 부탁드려도 될까요..? 준비해서 PR보내주시면 감사드리겠습니다 ㅜ..ㅜ

**Comment by MPThLee** [comment]
정상적으로 빌드된 자체 부트로더, pyinstaller 4.3, x86의 결과는 많이 양호하네요. https://www.virustotal.com/gui/file/45920c7790a46134032d2a029aa67b0db87828b5e106d35a5bb1394aeb9f6c19/detection
일단 Microsoft 탐지가 없어졌고, 18/68에서 3/68로 줄어들었습니다. 이상태로 pr 넣겠습니다.

**Comment by SJang1** [comment]
> 정상적으로 빌드된 자체 부트로더, pyinstaller 4.3, x86의 결과는 많이 양호하네요. https://www.virustotal.com/gui/file/45920c7790a46134032d2a029aa67b0db87828b5e106d35a5bb1394aeb9f6c19/detection
> 일단 Microsoft 탐지가 없어졌고, 18/68에서 3/68로 줄어들었습니다. 일단 이 상태로 pr 넣겠습니다.

넹 감사합니다 :)

**Comment by SJang1** [comment]
Microsoft Trojan:Win32/Wacatac.B!ml

오진 여전하네요...

**Comment by MPThLee** [comment]
아마 요즘 백신들이 기본적으로 클라우드 기반 바이러스 탐지가 기본이다보니, 좀 늦게 반영되나봅니다.
처음 빌드됐을때는 문제 없이 결과가 나왔던걸 보면 일단은 기본적인 방식으로 한번 돌리고, 샘플을 보낸다음 스캔해서 결과가 바뀐거라고 생각합나디ㅏ.

**Comment by SJang1** [comment]
네. 저도 그렇게 보고 있고, 항상 오진은 Cloud에서 뜨고 있더라고요..

**Comment by SJang1** [comment]
기록용 - 탐지명 : `Program:Win32/Wacapew.C!ml`
