### ISSUE TITLE
병원 검색 이슈

### ISSUE THREAD

**Issue by jihoontack** [SJang1/korea-covid-19-remaining-vaccine-macro#346]
안녕하세요

https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/issues/82 에 있는 걸 전부 설정했는데 다음과 같이 실행이 되고 있습니다 (다른 분들 보면 검색되는 병원명이 뜨는 거 같은데, 저는 안 뜨네요ㅠ)
- 카카오 지갑알림 신청도 해두었고, 좌표는 친구는 잘 작동되는 좌표를 사용 중에 있습니다.

현재 macOS Big Sur 11.4, chorme 92.0.4515.107 사용 중에 있습니다.
사용 중인 releases 버젼은 1.0.17입니다.

혹시 예상 가는 issue가 있을까해서 달아둡니다
감사합니다.

![스크린샷 2021-07-28 오전 11 24 22](https://user-images.githubusercontent.com/43670621/127253954-35e356d4-da1a-4066-b889-8a45e4dfecb8.png)

**Comment by SJang1** [comment]
`127.` , `37.`을 포함해서 입력해주셔야 합니다.
