### ISSUE TITLE
vaccine-run-kakao-mac 버전 실행이 되지않습니다.

### ISSUE THREAD

**Issue by HanJaeHyuck** [SJang1/korea-covid-19-remaining-vaccine-macro#358]
문서 ‘vaccine-run-kakao-mac’을(를) 열 수 없습니다. 유니코드(UTF-8) 텍스트 인코딩이 적용되지 않습니다.
-파일이 다른 텍스트 인코딩을 사용하여 저장되었거나, 텍스트 파일이 아닐 수 있습니다.

이런 오류가 뜨는데 해결 방법이 있나요?

**Comment by SJang1** [comment]
터미널에서 `chmod +x vaccine-run-kakao-mac`을 실행하셔서 실행 가능한 파일로 변환 후 실행하시면 됩니다.

**Comment by htjung94** [comment]
감사합니다!
