### ISSUE TITLE
pretty_print JSON Decode issue

### ISSUE THREAD

**Issue by dhgwag** [SJang1/korea-covid-19-remaining-vaccine-macro#359]
안녕하세요. 귀한 코드 공개해주셔서 감사드립니다.

사용 중 발견된 에러가 있어 전달드립니다. 

추측컨데 requests로 받아온 데이터에 뭔가 문제가 있는 경우 정상적으로 디코딩이 안되는 이슈같네요. (정상적으로 잘 돌다가 가끔 저럽니다.)

pretty_print 내부에 try except를 넣는게 어떨지 제안드립니다.

에러시 json_string 변수의 raw값 필요하시면 알려주세요. 지금은 exe로 돌리고 있는데, 코드 수정해서 돌릴 수 있어요~!

![image](https://user-images.githubusercontent.com/19239391/127256251-4ee53c12-2dbc-4e58-92da-1bc6a749481a.png)

**Comment by SJang1** [comment]
네네 raw값이 있으면 아무래도 더욱 원인을 파악하는데 좋겠습니다. 부탁드리겠습니다 :)

**Comment by lemon-mint** [comment]
``` html
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
resp :504

**Comment by dhgwag** [comment]
에러 발생 시 pretty_print()의 parameter로 들어오는 json_string 값입니다.

네트워크 문제랑 관련이 있나보네요...

지금 컴퓨터 총 세 대 (집, 학교, 서버)로 테스트 중인데, 동일 에러가 모든 환경에서 간헐적으로 발생하는 것으로 볼 때 개인적인 환경 문제는 아닌 것으로 보입니다^^

예외처리를 해주는게 맞을 것 같네요

\<html>
\<head>\<title>504 Gateway Time-out\</title>\</head>
\<body>
\<center>\<h1>504 Gateway Time-out\</h1>\</center>
\<hr>\<center>nginx</center>
\</body>
\</html>

**Comment by SJang1** [comment]
네 확실히 카카오/질본 서버 문제네요~.....

raw 로그 감사드립니다!

**Comment by SJang1** [comment]
Main 브랜치에 업데이트 올렸습니다. Release 이후 이슈 Close하겠습니다. 감사합니다 👍

**Comment by dhgwag** [comment]
고생많으십니다 :) 감사합니다!
