### ISSUE TITLE
알수없는 이유로 예약이 불가합니다

### ISSUE THREAD

**Issue by hasukmin12** [SJang1/korea-covid-19-remaining-vaccine-macro#371]
![알수없는이유 에러](https://user-images.githubusercontent.com/56622945/127258447-0b1cc42f-f892-4640-b308-ec4396fb9c52.jpg)

매크로 첫 작동시에 위와 같은 에러가 발생했습니다..
이후 끄고 다시 작동시키는데

문제 없이 작동되는듯 해보이지만 
이후 3시간 가량 아래와 같은 예약 시도후 선착순 마감 화면만 50번 넘게 보고 있습니다.

![선착순 마감 1](https://user-images.githubusercontent.com/56622945/127258674-c460fd36-44bc-4a83-90dd-e5f9e1614815.png)

무슨 문제일까요?

**Comment by SJang1** [comment]
첫 사진은 카카오 서버 문제,
두번째 사진은 그저 말그대로 접종마감입니다.
