### ISSUE TITLE
덕분에 백신 맞고 왔어요!

### ISSUE THREAD

**Issue by haha9837** [SJang1/korea-covid-19-remaining-vaccine-macro#380]
안녕하세요~

한 3주? 4주 가량 잔여백신 새고만 하다가...운좋게 알게되어 
오늘 아침에 해봤는데 프로그램 돌린지 10분? 15분 만에 백신 예약해서 백신 맞고 집에 왔어요.

너무너무 감사해서 감사하다는 말을 꼭 전하고 싶어서요.

앞으로 좋은 일만 가득하시고 돈 길만 걷길 바라겠습니다!

**Comment by SJang1** [comment]
감사합니다..! 만 여기는 Issues만 올려주세요!
