### ISSUE TITLE
좌표값 문의드립니다.

### ISSUE THREAD

**Issue by Sangyeob-Kim** [SJang1/korea-covid-19-remaining-vaccine-macro#413]
프로그램을 실행하니 y 좌표값이 37.xxxxx 로 되어있어서,
서울 경기 지역만 사용이 가능한 것 같습니다.

혹시 36.xxxxx인 지역에서도 사용이 가능할 지 여쭙습니다.

**Comment by SJang1** [comment]
37.xx은 예시입니다. 127.xx도 예시입니다.
37.xx / 36.xx 다 입력해주셔야 합니다.
