### ISSUE TITLE
좌표값 문의드립니다.

### ISSUE THREAD

**Issue by Sangyeob-Kim** [SJang1/korea-covid-19-remaining-vaccine-macro#414]
제가 찾고 싶은 사각형 영역의 y값이 37.xxxx가 아닌 36.xxxx인데, 이 경우도 예약이 가능할까요?

감사합니다.

**Comment by username15574** [comment]
그냥 36.xxxx 128.xxxx 이렇게 입력해도 되더라고요!

**Comment by SongRin** [comment]
36.xxxx로 입력하시면 돼요
