### ISSUE TITLE
백신 발견 후 예약되지 않음

### ISSUE THREAD

**Issue by tofusnack** [SJang1/korea-covid-19-remaining-vaccine-macro#421]
![image](https://user-images.githubusercontent.com/88075986/127272436-a5f1caa0-0c27-4105-80e0-3abdf5a1c81b.png)
백신 발견되었다고 노출되나, 카카오톡 지갑으로 확인 메시지가 오지 않습니다.

**Comment by SJang1** [comment]
현재 잔여백신 예약 서버가 과부화가 걸린 듯 합니다.
시간이 좀 지나면 괜찮아질 것으로 생각됩니다. 사용자가 많이 몰린 듯 싶습니다.

**Comment by SJang1** [comment]
지갑으로 알림이 오지 않았다면 예약이 되지 않은 것입니다.

**Comment by tofusnack** [comment]
터미널은 그냥 두면 알아서 갱신 될까요? 아니면, 종료 후 시간이 좀 지난 후에 다시 시도 해야 할까요?

**Comment by SJang1** [comment]
종료 후, 나중에 시도하는 편이 더 나을 것으로 보입니다.
