### ISSUE TITLE
pc자체에서 프로그램 다운로드가 안됩니다. 

### ISSUE THREAD

**Issue by ellykeem** [SJang1/korea-covid-19-remaining-vaccine-macro#424]
윈도우 유저인데
크롬에서 다운로드 후 실행하려는데 아래 메시지가 뜹니다.

현재 pc에서는 이 앱을 실행할 수 없습니다.  pc 버전을 찾으려면 소프트웨어 게시자에게 문의하세요

what's the problem?

**Comment by SJang1** [comment]
백신 프로그램이 실행을 차단하고 있는건 아닌지 확인해보세요.
또한, OS가 32비트이면 실행이 안 될 수 있습니다.

**Comment by ellykeem** [comment]
네. 32비트네요.. ㅜㅜ 감사합니다
