### ISSUE TITLE
대부분 발견만하고 예약 신청이 안됩니다.

### ISSUE THREAD

**Issue by thekingofpsycho** [SJang1/korea-covid-19-remaining-vaccine-macro#428]
10번중에 한번은 '마감됐습니다' 하고 json 값이 출력되긴 했는데
대부분의 경우 발견했습니다 만 뜨고 그 뒤에 기다려도 아무런 응답이 없네요.
신청에 실패한건가요?

**Comment by loolloo1004** [comment]
![백신](https://user-images.githubusercontent.com/88076472/127274027-3339914a-93fb-4165-bb88-52f3b079eaf7.jpg)
저도 이렇게만 뜨고 멈추는데.. 왜 이러는 건가요?

**Comment by SJang1** [comment]
잔여백신 서버가 (아마도 이용자가 너무 많아) 죽은 상태입니다.

**Comment by loolloo1004** [comment]
계속 백신만 발견했다고 하고.. 예약시도는 안되는데.. 왜이러는 거예요..
![image](https://user-images.githubusercontent.com/88076472/127274627-8c053024-cf59-4c7b-a1b2-e127cfcf5edf.png)

**Comment by thekingofpsycho** [comment]
아 맞네요 감사합니다!

**Comment by SJang1** [comment]
ESC키를 눌러보세요. "선택"된 상태에서는 화면이 넘어가지 않습니다.

**Comment by loolloo1004** [comment]
계속 발견만 하고.. 멈춤니다.. 예약 시도는 어케해야 하는것인가요?
카카오톡 따로 설정해 줘야 하는것 있나요?

**Comment by SJang1** [comment]
잔여백신 서버가 (아마도 이용자가 너무 많아) 죽은 상태입니다.. 신청이 안되는 이유가 이것 때문입니다.

**Comment by loolloo1004** [comment]
korea-covid-19-remaining-vaccine-macro-1.0.17 파일 받고 - 압축풀고 - vaccine-run-kakao-windows 파일 받아서 
korea-covid-19-remaining-vaccine-macro-1.0.17 폴더에 vaccine-run-kakao-windows 파일 집어넣고 - 실행 - 좌표찍고 하는것 해서 정상 으로 돌아가는건 확인이 되는데..
백신 발견 확인만 하고 멈추네요..
예약 시도를 하지 않는데.. 
폴더안의 파일에서 따로 설정해줘야 하는것 있나요?

**Comment by MPThLee** [comment]
예약 시도한것이 맞습니다. 근데 서버가 터져가지고 응답이 안돌아와서 그런거에요.
