### ISSUE TITLE
If TIMEOUT change URL

### ISSUE THREAD

**Issue by SJang1** [SJang1/korea-covid-19-remaining-vaccine-macro#445]
If timeout URL changes to : 
 https://vaccine.kakao.com/api/v1/reservation/retry

and retries once.

Need to also do this

**Comment by skarlans** [comment]
안그래도 그 부분을 request.post에 timeout kwarg를 넣어서 다시 시도하는 식으로 바꿔놨었는데
위 말씀대로면 reservation_url을 위 url로 바꾸고 post메소드 돌리면 된다는 말씀이신가요?

**Comment by SJang1** [comment]
TIMEOUT된 경우에 한해서 해당 url로 접근을 시도하게 됩니다.

**Comment by skarlans** [comment]
넵 감사합니다.

**Comment by kmgququ** [comment]
어떻게 적용하나요..? ㅠ

**Comment by SJang1** [comment]
> 어떻게 적용하나요..? ㅠ

수정 예정인 내용입니다.

**Comment by kmgququ** [comment]
지금 예약시도중 오류 말씀하시는 건가요?
