### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by san9569** [SJang1/korea-covid-19-remaining-vaccine-macro#447]
안녕하세요. 너무 유용한 자료 공유 감사드립니다.

macOS로 실행중인데 해당 오류가 서칭하면서 이따금씩 발생하여 원인 여쭤봅니다.
개인 이슈일 수도 있겠지만 확인 부탁드립니다 감사합니다
<img width="760" alt="스크린샷 2021-07-28 오후 4 44 31" src="https://user-images.githubusercontent.com/60248657/127284119-25e207b1-1680-475b-b2ca-1690415f0d89.png">

**Comment by SJang1** [comment]
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/issues/359
