### ISSUE TITLE
모듈 설제 에러

### ISSUE THREAD

**Issue by wook8905** [SJang1/korea-covid-19-remaining-vaccine-macro#463]
안녕하세요~
코드 공유 해주셔서 감사합니다.

크롬 설정 이후 exe파일로 실행 하니 아래의 사진처럼 오류 나왔습니다.
![image](https://user-images.githubusercontent.com/88084752/127299027-2d8da457-0906-4d79-a8c1-50dbc8a0f6ff.png)

파이썬 프로그램으로 실행하니 아래의 에러로 나와
C:\Users\user\anaconda3\python.exe C:/Users/user/Downloads/korea-covid-19-remaining-vaccine-macro-main/korea-covid-19-remaining-vaccine-macro-main/vaccine-run-kakao.py
Traceback (most recent call last):
  File "C:/Users/user/Downloads/korea-covid-19-remaining-vaccine-macro-main/korea-covid-19-remaining-vaccine-macro-main/vaccine-run-kakao.py", line 3, in <module>
    import browser_cookie3
ModuleNotFoundError: No module named 'browser_cookie3'

Process finished with exit code 1

모듈 설치 어떻게 해야 하나요?
기존에 있던 방법을 다 써봐도 안됩니다 ㅜㅜ

**Comment by SJang1** [comment]
현재 카카오측 서버 장애로 사용자 정보를 못 불러오고 있습니다.
