### ISSUE TITLE
Actions에 올라온 exe 파일 튕김

### ISSUE THREAD

**Issue by username15574** [SJang1/korea-covid-19-remaining-vaccine-macro#469]
![화면 캡처 2021-07-28 201812](https://user-images.githubusercontent.com/88074807/127319562-34094249-5f38-4137-93ac-eb87739cadf9.png)
실행후 Y를 입력하고 엔터치면 거의 0.2초만에 종료됩니다

**Comment by SJang1** [comment]
아직 머지 안된 PR로 개발중인 버전입니다.
main 브랜치의 exe를 이용해주세요

**Comment by username15574** [comment]
아!.... 나대서 죄송합니다!
