### ISSUE TITLE
오류가...

### ISSUE THREAD

**Issue by hwnil** [SJang1/korea-covid-19-remaining-vaccine-macro#498]
2021-07-29 11:10:49.989820
JSONDecodeError :  Expecting value: line 1 column 1 (char 0)
JSON string :  <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>

Press Enter to close...

이런것이....

**Comment by SJang1** [comment]
카카오 서버 오류입니다.
