### ISSUE TITLE
exe 말고 소스코드도 바이러스 검진

### ISSUE THREAD

**Issue by changdocjjang** [SJang1/korea-covid-19-remaining-vaccine-macro#524]
![image](https://user-images.githubusercontent.com/87104616/127433028-a2366e10-5484-461d-8675-d279c7525c62.png)
exe만 바이러스로 판단하던데 소스코드 파이썬 파일도 바이러스로 인식하네요

**Comment by MPThLee** [comment]
자체 빌드 부트로더를 포함한게 문제인거같네요. 음...
