### ISSUE TITLE
mac용 프로그램 다운 시 문제점

### ISSUE THREAD

**Issue by htjung94** [SJang1/korea-covid-19-remaining-vaccine-macro#527]
mac용 카카오 매크로 프로그램 다운해서 실행할려고하면 '유니코드(UTF-8) 텍스트 인코딩이 적용되지 않습니다'라고 뜨면서 실행이 안되는데 어떻게 해야할까요??ㅠㅠㅠ

**Comment by sh-cho** [comment]
- https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/issues/358#issuecomment-887974668
해당 이슈 참고부탁드립니다
