### ISSUE TITLE
카카오톡 로그인 이슈

### ISSUE THREAD

**Issue by dpdlfjsfh** [SJang1/korea-covid-19-remaining-vaccine-macro#549]
크롬 주의사항을 따르고, 로그인을 유지한채로 실행해도
사용자 정보를 불러오는데 실패하였습니다.
Chrome 브라우저에서 카카오에 제대로 로그인되어있는지 확인해주세요.
로그인이 되어 있는데도 안된다면, 카카오톡에 들어가서 잔여백신 알림 신청을 한번 해보세요. 정보제공 동의가 나온다면 동의 후 다시 시도해주세요.
의 문구가 나온다면 크롬의 문제일까요?

**Comment by woosa0502** [comment]
https://vaccine.kakao.com/api/v1/user
저도 저기들어가보면 계정정보가 나오는데 매크로에서는 계속 계정정보를 못불러오네요

**Comment by woosa0502** [comment]
관리자권한으로 실행하니 됐습니다
