### ISSUE TITLE
vaccine-run-kakao-mac이 설치되지 않습니다

### ISSUE THREAD

**Issue by yuniverse96** [SJang1/korea-covid-19-remaining-vaccine-macro#558]
문서 vaccine-run-kakao-mac 을 열 수 없습니다. 유니코드(UTF-8)텍스트 인코딩이 적용되지 않습니다. 라고 떠서 텍스트 편집기 설정을 한국어(Windows,DOS)로 변환했으나 여전히 파일을 열 수가 없다는 경고창이 뜹니다. 이 문제는 어떻게 해결해야하나요?

**Comment by jezsung** [comment]
#358

**Comment by angcumfox** [comment]
터미널 실행후 cd Downloads(다운로드 폴더에 파일이 있을 경우) 입력 후 엔터,
chmod +x vaccine-run-kakao-mac 명령어 입력 후에 엔터 치고 다시 폴더로 들어가면 exe파일로 실행 가능하실거에요! 그리고 실행 후에 조금 기다리면 비밀번호 2번 입력하면 됩니당
