### ISSUE TITLE
permission denied_ config.ini

### ISSUE THREAD

**Issue by JasminePark43** [SJang1/korea-covid-19-remaining-vaccine-macro#592]
![permission denied](https://user-images.githubusercontent.com/88124551/127584622-6a7b66ff-2b22-4c68-9231-8ac41d97269f.png)

 어떻게 해결할 수 있을까요?

어제 잠깐 괜찮다가 오늘 다시 전혀 실행이 안되고 해당 오류가 뜹니다..

**Comment by SJang1** [comment]
권한을 확인해보세요.

**Comment by JasminePark43** [comment]
> 권한을 확인해보세요.

어디서 어떤 권한을 확인해야 하나요 ㅠㅠ
