### ISSUE TITLE
for Mac 카카오 로그인 문제

### ISSUE THREAD

**Issue by jxxnnee** [SJang1/korea-covid-19-remaining-vaccine-macro#595]
https://vaccine.kakao.com/api/v1/user

해당 링크로 들어가면 제 정보가 잘 나오는데도 불구하고

"사용자 정보를 불러오는데 실패하였습니다.
Chrome 브라우저에서 카카오에 제대로 로그인되어있는지 확인해주세요.
로그인이 되어 있는데도 안된다면, 카카오톡에 들어가서 잔여백신 알림 신청을 한번 해보세요. 정보제공 동의가 나온다면 동의 후 다시 시도해주세요."

라는 문구가 계속 반복해서 나오네요,,
관리자 권한의 문제인가 싶어
sudo 를 붙여서 실행해도 같은 결과입니다.

혹시 해결 방법이 있을까요?

**Comment by SJang1** [comment]
Profile이 기본 프로파일인지 확인해보세요.
또한, 관련된 이슈와 디스커션 많으니 확인해봐주세요.
