### ISSUE TITLE
(긴급) 대기중, 마감, 없음 중 없음이 목록에 안 뜨는 현상

### ISSUE THREAD

**Issue by wuhancorona** [SJang1/korea-covid-19-remaining-vaccine-macro#605]
안녕하세요.

어제까지만 해도 목록에 "없음"까지 다 떴는데(실제 확인해봄) 오늘 동일한 설정 그대로 

해보니 카카오맵 기준 "없음"이 목록에 뜨지 않습니다. 이 병원이 오늘 한 번은 잔여백신

있었다는 뜻인데 "없음"이 많은 곳을 다시 지정해서 돌리면 딱 "없음" 병원만 빼고 예약을 

시도하네요. 카카오에서 막은 건지는 모르겠지만 긴급한 사항 같습니다. 최신 버전입니다.

**Comment by SJang1** [comment]
없음은 원래부터 목록에만 표시되지 않았을 뿐이지, `없음 -> 재고발생` 시 정상적으로 예약을 진행합니다. 버그나 문제가 생긴 부분이 아닙니다.

**Comment by MPThLee** [comment]
원래 안나오는게 맞습니다. https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/blob/4fdcf3c6d51db1caa4b7b5af16759a0d3f770813/vaccine-run-kakao.py#L165
없음의 경우 `EXHAUSTED`상태라 출력이 안되는게 정상입니다.

**Comment by wuhancorona** [comment]
감사합니다! ㅎㅎ
