### ISSUE TITLE
1.0.6 작동안되는 에러 입니다

### ISSUE THREAD

**Issue by 38sun** [SJang1/korea-covid-19-remaining-vaccine-macro#62]
윈도우 10 사용하고있고요
1.0.5는 작동이 되는데
1.0.6 은 작동이 안되기에 파이썬에서 에러코드 첨부해주실수있냐하셔서
파이썬설치해서 실행한것같은데 이런 메세지가 나오기에 첨부해드립니다

![에러](https://user-images.githubusercontent.com/87807347/126861481-7848b0a6-35d7-4057-8a04-c2c718546578.JPG)

**Comment by Jayyyy-04** [comment]
해당 문제는 코드의 문제가 아니라 Module이 설치가 안되셔서 뜨는것 같습니다. 터미널에서 'pip install requests' 따옴표 제외하고 입력하셔서 Module설치 하시면 정상적으로 동작하실 겁니다.

**Comment by 38sun** [comment]
> 해당 문제는 코드의 문제가 아니라 Module이 설치가 안되셔서 뜨는것 같습니다. 터미널에서 'pip install requests' 따옴표 제외하고 입력하셔서 Module설치 하시면 정상적으로 동작하실 겁니다.

감사합니다 뭔가설치가 되더니 작동되네요
저는 초보라exe 다운받아서 작동이 안되었는데 모듈 설치후에는 exe화일도  작동되네요 감사합니다
