### ISSUE TITLE
카카오잔여백신 신청시 병원누락 이슈

### ISSUE THREAD

**Issue by yeongeunSon** [SJang1/korea-covid-19-remaining-vaccine-macro#656]
윈도우 : 10, 크롬 : 92.0.4515.107 (공식 빌드) (64비트), 사용중입니다.
설정해 놓은 좌표 안에 있는 일부 병원의 정보를 받아오지 못하는것 같습니다.
설정한 좌표는 (127.043183, 37.435175) (127.177717, 37.340899) 이고 병원의 좌표는(127.107262, 37.400347)입니다. 
릴리스 프로그램과 파이썬 파일 둘 다에서 같은 현상이 발생합니다. 

(혹 이슈 질문 양식이 잘못되었다면 죄송합니다..!)

**Comment by SJang1** [comment]
너무 범위가 크면 일부 병원 정보가 안불러와질 수 있습니다.
또한, 마감된 병원과 없음 상태인 병원은 리스트에 불러와지지 않습니다만, 예약은 정상적으로 시도됩니다.
