### ISSUE TITLE
유니코드 문제

### ISSUE THREAD

**Issue by plusc98** [SJang1/korea-covid-19-remaining-vaccine-macro#657]
한글로 프로그램이 변경되면서 비한글 윈도 환경에서 글자가 [?]로 깨져보입니다....
![image](https://user-images.githubusercontent.com/88180772/127609958-1d4196cd-e213-4d0e-a840-3ae00dfb7ced.png)

**Comment by SJang1** [comment]
혹시 정확한 환경이 어찌 되는지 알 수 있을까요?
Windows 버전, Windows 언어설정 부분을 위주로 부탁드립니다.

**Comment by plusc98** [comment]
윈도는 Windows 10 Pro, 버전은 21H1이고 OS Build는 19043.1110입니다. 언어는 English (United States)고, 지역설정은 Korea, Regional Format은 English (United States)입니다.

**Comment by SJang1** [comment]
동일한 환경에서 테스트해보기 위해 약간 시간이 소요될 수 있습니다. 정보 감사합니다 :)

**Comment by plusc98** [comment]
희한한게...언어 한국어로 바꾸고 Regional Format을 한국어로 바꿔봤는데도 마찬가지로 뜹니다..

![image](https://user-images.githubusercontent.com/88180772/127610927-83865ce2-ca3e-4d72-900b-7a2d7ff01515.png)

**Comment by plusc98** [comment]
cmd 인코딩 문제로 확인하였습니다. cmd font를 바탕체로 변경 후 문제가 해결되었습니다.

![image](https://user-images.githubusercontent.com/88180772/127611502-8f927716-4795-4f7c-b32d-7573c2120232.png)

신경써주셔서 감사합니다!

**Comment by MPThLee** [comment]
저거는 폰트 문제일거에요. 저도 예전에 저러다가 어느순간 고쳐졌어요... 왜 고쳐졌는지는 아직도 의문입니다만 ㅋㅋ;;;;
