### ISSUE TITLE
프로세스가 갑자기 종료되는 경우가 있습니다. 정상작동인지 모르겠습니다.

### ISSUE THREAD

**Issue by miusic** [SJang1/korea-covid-19-remaining-vaccine-macro#69]
안녕하세요! 
이용방법에 알려주신대로 설정하고, 새로고침 시간과 브라우저를 여는 지연시간을 각각 다르게 설정해서 시도를 하고 있었습니다.
총 3개의 프로세스를 실행중이었고, 각각 시간설정은
(새로고침 주기, 브라우저 열기 지연시간) 순으로 (0.2,0), (0.1,0.2), (0.2,0.1)로 설정해 두었습니다

그런데, 잘 실행이 되다가 어느순간 프로세스가 종료가 되는 현상이 있어서 질문드립니다.
크롬 브라우저는 켜둔 상태였고, 따로 예약실패 창이나 탭이 열리거나 하지는 않았습니다.
exe파일로 실행시킨거라 found가 떴는지 확인할 길이 요원하네요..
혹시 이렇게 되어도 예약시도가 제대로 되고 있는걸까요?
읽어주셔서 감사합니다.

**Comment by SJang1** [comment]
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/discussions/68#discussioncomment-1046297

서버쪽의 문제로 정상작동하지 않고 종료되던걸로 보입니다.
해당 부분 수정 예정입니다.

프로세스가 갑자기 중단되는 경우 오류로그를 보일 수 있도록 하는 업데이트가 진행되어야 할 것으로 보이네요.

**Comment by miusic** [comment]
빠른 답변 감사드립니다!
업데이트 되면 다시 시도 해보겠습니다

**Comment by SJang1** [comment]
644c3e77284077958aa82aad4556da82cecafc72 와 0b84ca7b39e3c59922d489b1de34e4cc9600eb2c 로 수정되었습니다. 테스트 완료 및 배포 후 이 이슈는 close하겠습니다.

파이썬 파일로 master을 받아서 실행 시 이 이슈는 Fix된 채로 사용하실 수 있습니다.

**Comment by miusic** [comment]
감사합니다!
시도해보겠습니다

**Comment by Sang921** [comment]
먼저 제작자님 덕분에 편하게 사용하고있습니다 감사합니다.
저도 돌리다보면 팅기는 경우가 있더군요 ...
물론 새로 고쳐주신버전으로 다시 설치했을때 기준입니다..
그전보다 덜꺼지는거같긴한데.. 꺼지는건 아직도있어요 ㅠㅠ

**Comment by SJang1** [comment]
@miusic @Sang921 혹시 exe로 실행하셨나요 아니면 `python3 vaccine-run-kakao.py`로 실행하셨나요?
아직 exe파일은 업데이트 안되었습니다.

**Comment by miusic** [comment]
아.. exe로 실행했었습니다
내일 다시 파이썬 파일로 해보겠습니다. 감사합니다!

**Comment by SJang1** [comment]
exe 배포 완료했습니다!
