### ISSUE TITLE
타이머 지정 개선요청

### ISSUE THREAD

**Issue by natura4917** [SJang1/korea-covid-19-remaining-vaccine-macro#699]
search_time 도 별도로 받게 했으면 좋겠네요.

별도 빌드해서 사용하고 있습니다.

**Comment by ChungmaruQ** [comment]
시간을 더 아래로 낮춰도 IP나 계정 블락 없으시던가요??

**Comment by natura4917** [comment]
시간을 더 낮추면 위험할듯 하네요
저같은 경우는 여러개 돌릴땐 오히려 높게 잡았습니다
