### ISSUE TITLE
사용자가 원하는 경우에 잔여백신이 발견되어도 계속 작동할 수 있도록 설정

### ISSUE THREAD

**Issue by SJang1** [SJang1/korea-covid-19-remaining-vaccine-macro#70]

**Comment by SJang1** [comment]
08f198aed13ea78185a3cfa562ca33fc7aeb62cb 로 추가완료. Test 후 Close

**Comment by dlddnd** [comment]
잔여백신 발견 시 예약시도를 하고, 실패나 성공을 해도 매크로는 계속 작동하는 설정인가요?

**Comment by SJang1** [comment]
> 잔여백신 발견 시 예약시도를 하고, 실패나 성공을 해도 매크로는 계속 작동하는 설정인가요?

네

**Comment by SJang1** [comment]
이 방식은 취소되고 완전자동화로 가닥을 잡았습니다.
