### ISSUE TITLE
tmp_cookie_file를 읽는과정에서 퍼미션오류가나네요

### ISSUE THREAD

**Issue by JINHYUKJEONG** [SJang1/korea-covid-19-remaining-vaccine-macro#740]
PermissionError: [WinError 32] 다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다: 'C:\\Users\\~~~\\~~.sqlite'
browser_cookie3모듈자체 오류인지..흠

**Comment by MPThLee** [comment]
#82 를 따라해보시고 안되면 크롬을 끄신 후 실행해보시길 바랍니다.

**Comment by SJang1** [comment]
혹시 시스템이 ARM기반이신가요?

**Comment by JINHYUKJEONG** [comment]
> 혹시 시스템이 ARM기반이신가요?

AMD64입니다
