### ISSUE TITLE
위치 하단 좌측우측 입력시 잘못된 정보라고하네요

### ISSUE THREAD

**Issue by akakakakak1** [SJang1/korea-covid-19-remaining-vaccine-macro#742]
확인 부탁드려요!! 내일 돌려보기 전에 오늘 확인 한번 해봣는데 안되더라구요 좌표 입력이.

**Comment by SJang1** [comment]
좌표값을 알려주세야 확인이 가능합니다.. 37 또는 127과 같은 정수자리도 입력하신게 맞나요...?

**Comment by minkyu1237** [comment]
127.168343
37.464273
127.057255
37.547420

**Comment by minkyu1237** [comment]
확인 한번 부탁드려요!

**Comment by dhgwag** [comment]
좌상단 좌표가 먼저 입력돼야 합니다.

적어주신 좌표 보면 우하단 좌표 먼저 입력하신 것 같네요

**Comment by SJang1** [comment]
그러고보니 좌상단 우하단이 서로 뒤집힌거처럼 보이기도 하네요. 잠시 문제가 있는 코드좀 정리하고 오겠습니다.

**Comment by akakakakak1** [comment]
> 좌상단 좌표가 먼저 입력돼야 합니다.
> 
> 적어주신 좌표 보면 우하단 좌표 먼저 입력하신 것 같네요

원래 쓰던 좌표 썻습니다~ 확인해보세여

**Comment by dhgwag** [comment]
> > 좌상단 좌표가 먼저 입력돼야 합니다.
> > 적어주신 좌표 보면 우하단 좌표 먼저 입력하신 것 같네요
> 
> 원래 쓰던 좌표 썻습니다~ 확인해보세여

입력 순서를 맞춰서 쓰셔야합니다.
1. 좌상단x 
2. 좌상단y 
3. 우하단x
4. 우하단y
순서로요.

적어주신 좌표를 맞게끔 정렬하면
127.057255
37.547420
127.168343
37.464273

가 되겠네요. 이렇게 한번 해보시겠어요?

**Comment by SJang1** [comment]
일단 핫픽스 올렸습니다. 약 15분 후 올라오는 Release를 이용해주세요.

**Comment by SJang1** [comment]
@dhgwag 제 쪽에서도 좌표문제가 있는걸 발견했습니다..

**Comment by akakakakak1** [comment]
> @dhgwag 제 쪽에서도 좌표문제가 있는걸 발견했습니다..

네 감사합니다!!

**Comment by SJang1** [comment]
핫픽스 릴리즈 올렸습니다

**Comment by akakakakak1** [comment]
좌표 입력까지는 되는데 목록이 안뜨네요 ... 항상 수고가 많으십니다!
