### ISSUE TITLE
{"code":"NO_SUITABLE","desc":"선택하신 잔여백신의 \n접종 가능한 연령이 아닙니다.",가 뜹니다

### ISSUE THREAD

**Issue by tentenro** [SJang1/korea-covid-19-remaining-vaccine-macro#749]
ven00013,14,any로 해도 모두 동일하게 에러가 발생합니다. 
이전버전에서는 해당 문제 없이 사용했었고, 
20대 2명의 아이디 모두에서 해당 이슈가 발생했습니다

**Comment by jinh0** [comment]
20대는 Any 에 해당 되지 않습니다 (아스트라제네카/얀센은 30세 이상) 문제가 있습니다.

VEN00013,14 에 대해서는 `config.ini` 파일 보여줄 수 있나요?

**Comment by tentenro** [comment]
[config]
vac =  ven000013
topx = 126.770789
topy = 37.601161
botx = 126.867215
boty = 37.495184
 
로 시행했습니다. 
-----Original Message-----

**Comment by jinh0** [comment]
백신 이름에 숫자 0이 3개만 있습니다. VEN000013이 아니라 VEN00013입니다.

**Comment by sh-cho** [comment]
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/blob/c22bc9dbc242a2e8f8421ec346f0cee5b0c1959f/vaccine-run-kakao.py#L207-L208

혹시 지금 head 위치가 최신 맞나요? 후보에 없는 백신 코드명이면 다시 입력받게 해놨던거같아서요

**Comment by tentenro** [comment]
00013으로 했을 때도 동일한 오류가 발생합니다.
 
2021-08-02 13:48:15.699034
서울수가정의학과의원 에서 백신을 2개 발견했습니다.
주소는 : 경기 부천시 여월로 72 입니다.
ven00013 으로 예약을 시도합니다.
ERROR. 아래 메시지를 보고, 예약이 신청된 병원 또는 1339에 예약이 되었는지 확인해보세요.
{"code":"NO_SUITABLE","desc":"선택하신 잔여백신의 \n접종 가능한 연령이 아닙니다.","organization":{"orgCode":"41326946","orgName":"서울수가정의학과의원","confirmId":"365120504","phoneNumber":"032-677-8575","address":"경기 부천시 여월로 72","x":126.80633315911071,"y":37.51175501406178,"openHour":{"date":"2021-08-02","dayOfWeek":"월요일","dayOff":false,"openHour":{"start":"10:00","end":"16:00"},"lunch":{"start":"13:00","end":"14:00"}},"disabled":false}}
Press Enter to close...
 
[config]
vac =  ven00013
topx = 126.770789
topy = 37.601161
botx = 126.867215
boty = 37.495184

 
-----Original Message-----

**Comment by tentenro** [comment]
기존 config에 y로 사용하다가 새로 입력했더니 해결되었습니다 감사합니다 
-----Original Message-----
