### ISSUE TITLE
쿠키를 직접 config.ini에 저장하기

### ISSUE THREAD

**Issue by jinh0** [SJang1/korea-covid-19-remaining-vaccine-macro#751]
저는 크롬 브라우저로 인증 할라고 계속 했는데 문제가 있어서 직접 `_kawlt` 카카오 인증 쿠키를 프로그램 속안에 넣어서 성공했습니다 (discussed in #750 ).

프로그램 파일 속안에 `main_function()`에 `load_cookie()` 지우고 이 코드를 썼습니다:
<img width="493" alt="Screen Shot 2021-08-02 at 12 48 09 PM" src="https://user-images.githubusercontent.com/40512164/127801910-6d7e85e9-b827-45a1-83dd-293fe6820f8a.png">

그러므로서, 미래에 크롬 브라우저로 인증 안되는 사람들 위해서 직접 `config.ini`에 쿠키를 저장 하는 기능성은 어때요? 혹시 이렇게:
<img width="393" alt="Screen Shot 2021-08-02 at 12 54 51 PM" src="https://user-images.githubusercontent.com/40512164/127802333-9b988cf1-7e34-4dd8-9f9c-247dae294bb6.png">

괜찮으면 PR을 만들겠습니다.

---

TL;DR Because I was having issues with the `browser_cookie3` library accessing my `.kakao.com` Chrome browser cookies, I manually got the authentication cookie (the `_kawlt` cookie) from Inspect Element and set it to the global `jar` variable.

I am suggesting a new feature that would allow users to directly save and edit the cookie value in `config.ini` as illustrated in the 2nd image. I'm willing to make a PR for this if you think it's a good idea.

**Comment by SJang1** [comment]
config말고 cookie.ini 파일에 하는게 더 나을 것 같긴 한데, 좋은 아이디어입니다! 👍

**Comment by jinh0** [comment]
네, 다 되면 PR 만들겠습니다!
