### ISSUE TITLE
다운받는 파일에 아래와 같이 보안 이슈가 있다고 하는데 문제없나요? (아까 올렸는데 삭제되어 다시 문의드립니다.)

### ISSUE THREAD

**Issue by chanhojung** [SJang1/korea-covid-19-remaining-vaccine-macro#770]
![image](https://user-images.githubusercontent.com/29187928/127826180-b659abc3-a8c2-49cc-8cc7-acd08fb5c76f.png)

**Comment by ssvaccine** [comment]
오진입니다

**Comment by SJang1** [comment]
오진입니다. 삭제된게 아니라 Closed된겁니다.
