### ISSUE TITLE
api가 바뀌었습니다.

### ISSUE THREAD

**Issue by MPThLee** [SJang1/korea-covid-19-remaining-vaccine-macro#774]
![image](https://user-images.githubusercontent.com/26970092/127850619-ba6ac8ab-5b05-439b-9682-1a5d0605c133.png)
`left_count_by_coords`가 `v2`에서 `v3`로 변경되었네요.

다른 api들이 얼마나 바뀌었는지는 확인 못했습니다.

#781 #742 랑 연관된 문제일수도 있습니다.

**Comment by rigizer** [comment]
> 제가 몰라서 물어보는데, 이런 API request들을 어떻게 찾아요?

본인의 경우 Fiddler과 같은 프로그램으로 캡쳐해서 API 찾아내거나, Wireshark 패킷분석해서 찾고있습니다.
다른분들은 어떻게 찾으시는지 모르겠네요

**Comment by SJang1** [comment]
API가 바뀐게 여러개 보이네요. 곧 업데이트하겠습니다.

**Comment by SJang1** [comment]
실질적으로 API가 바뀌면서 바뀐 값은 안보이는데 왜 바꾼걸까요.. 🤔

**Comment by RunnableCode** [comment]
@SJang1 님 
기존 api 는 동작을 안하는 상태일까요?
list 는 잘 가져오는 것은 되는 걸로 보이는데요

**Comment by SJang1** [comment]
기존 API도 동작은 잘 합니다만, 매크로를 걸러내는 용도로 사용할 수 있기에 매우 빠른 시일 내에 업데이트가 필요한 사안입니다.

**Comment by RunnableCode** [comment]
업데이트 확인 할게요! 고맙습니다! 👍

**Comment by SJang1** [comment]
업데이트하였습니다 :)

**Comment by julian1z** [comment]
@SJang1 지금까지 목록만 뜨고 예약시도가 없던게 api가 바뀌어서 그런거였을까요??

**Comment by SJang1** [comment]
예약시도가 없었다면 예약시도 시 마다 멈췄어야하는데, 그런 일이 없던걸 보면 그저 늦었을 뿐이라고 짐작됩니다.

**Comment by RunnableCode** [comment]
방금 수정해서 예약 성공했습니다.
api version 변경에 따른 것인지는 잘모르겠어요
