### ISSUE TITLE
[1.0.28.] TypeError: option values must be strings

### ISSUE THREAD

**Issue by nomadreamer** [SJang1/korea-covid-19-remaining-vaccine-macro#807]
안녕하세요, 어제까지 1.0.27. 버전으로 잘 돌리고 있다가 오늘 공지를 보고 1.0.28. 버전으로 시도하니 오류가 나서 이슈 올립니다.

컴퓨터는 맥북이며, 실행은 Releases의 tar 파일이 아닌 전체 압축파일을 받아 파이썬을 돌렸습니다.
실행 결과는 아래와 같습니다.

<img width="1011" alt="스크린샷 2021-08-03 오후 2 39 46" src="https://user-images.githubusercontent.com/70120361/127963704-3f264381-f284-4792-b78c-94a89cfcd701.png">

기존의 파이썬 코드에서 제가 수정한 부분은 카카오톡 로그인 부분입니다.

<img width="853" alt="스크린샷 2021-08-03 오후 2 42 03" src="https://user-images.githubusercontent.com/70120361/127963893-fad28bd4-fbed-48d5-8656-03f3a87509a0.png">

공지사항에 있는 모든 방법들을 하나씩 동원해도 계속해서 로그인 오류가 발생하여,
#750 을 참고하여 직접 쿠키를 넣는 방식을 활용하였고, 1.0.27. 버전에서는 문제없이 돌아갔었습니다.

got_cookie 부분이 쿠키를 받아오는 부분이라고 생각하여 이전 버전과 동일한 방식으로 바꿔넣었는데 이번에는 오류가 발생하네요.

코드 수정 방식을 달리 해야 하는 것일까요? 아니면 다른 데에 문제가 있는 걸까요??

도움 주시면 감사드리겠습니다!

**Comment by moseoridev** [comment]
float(search_time)을 str(search_time)으로 하시면 될겁니다. 버그인지 뭔 이유가 있는지는.. 개발자분들이 금방 고쳐주실 것 같습니다.

**Comment by moseoridev** [comment]
#806 이미 수정해주셨네요

**Comment by nomadreamer** [comment]
감사합니다! 방금 저도 그렇게 해결했습니다!
