### ISSUE TITLE
크롬에 카카오 로그인이 되어있으나 exe파일 실행이 되지 않는 이슈

### ISSUE THREAD

**Issue by hiskyholic** [SJang1/korea-covid-19-remaining-vaccine-macro#81]
![image](https://user-images.githubusercontent.com/75426988/126896018-dd0a4c46-b2d7-4ae4-906a-d16225afaf4f.png)
정상적으로 로그인이 되어있으나 exe가 실행되지 않습니다.
스마트폰에서 알림 신청을 했을때 정보제공동의 창이 뜨는게 아닌 알림이 정상적으로 신청되었습니다가 나옵니다

**Comment by SJang1** [comment]
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/discussions/79 참고해주세요. 관련된 내용 곧 작성하겠습니다.
