### ISSUE TITLE
편의성 관련 기능 추가 제안드립니다.

### ISSUE THREAD

**Issue by paisano55** [SJang1/korea-covid-19-remaining-vaccine-macro#812]
들어가기에 앞서, 이런 편리하고 좋은 앱 개발해주셔서 너무 감사드립니다. 저와 부모님 백신 예약을 해보며 제 나름대로 프로그램을 약간씩 고쳐보았는데요, 이 중 간단하면서도 편리했던 것들 두 가지를 남겨봅니다. 

1. 사용자 정보 로딩 성공 시 사용자 이름을 출력하면 편할 듯 합니다.  부모님 백신 예약해드리겠답시고 켰다가 계정이 꼬여서 실수로 제 명의로 예약해버리는 일이 발생했습니다. 개발자 분께서 더 잘 아시겠지만, 함수 check_user_info_loaded에서 user_info['name']을 찍어주면 되는 것 같습니다.

2. 매 탐색마다 기관명과 상태를 찍어주는 대신, 탐색 범위 내 총 병원수와 현재 운영중인 병원수를 보여주는것도 괜찮을 듯 합니다. 수십~수백줄 프린트를 안해도 되어서 부하도 조금이나마 감소할것이고 탐색 범위를 조정하는데에도 도움이 될 듯 합니다. 저는 아래의 사진과 같이 수정하여 사용하였습니다.
![image](https://user-images.githubusercontent.com/41980902/127971885-ff0110ba-f69c-4afb-a4bb-02c877228bf4.png)

API와 같은 핵심적인 부분에서 기여할 수 있었다면 더 좋았겠지만, 제 실력이 너무 미흡하네요 ㅎ.

**Comment by SJang1** [comment]
2번 부분, 그렇게 하게되면 문제 있을때 문제를 찾거나 범위설정을 제대로 했는지 알기 어려워져서 개인적으로는 아니라고 봅니다.

**Comment by MPThLee** [comment]
사실 2번 부분은 과부화가 좀 있을 수 있어요. 매번 print하면 이상하게 좀 자원을 더 먹긴 하기때문에... 몇몇 알고리즘 테스트 사이트도 아예 stdout으로 보내던가 아예 한번에 출력하라곤 합니다.

근데 범위를 진짜 크게 잡는게 아닌이상 퍼포먼스 관련해선 별로 영향 없다고 생각합니다.

**Comment by SJang1** [comment]
1번 부분 추가해서 py파일에 올렸습니다.

**Comment by JiHunBae** [comment]
2번 부분 관련해서 글 적어봅니다. 디버그 모드와 실행 모드를 구분하는 입력을 받도록하여, 디버그 모드에서만 pretty_print 호출을 하는 것도 방법이라고 생각합니다. 저는 개발자님의 소스코드 그대로 실행해보았다가 좌표가 잘 설정되고 이상이 없다고 판단되면 pretty_print 를 주석처리한 후 동작시켰습니다.
