### ISSUE TITLE
잔여백신지도에서 지원하지 않는 환경이라합니다.

### ISSUE THREAD

**Issue by hyunjinnnn** [SJang1/korea-covid-19-remaining-vaccine-macro#817]
설정대로 했고

로그인시 주의사항에서 이 페이지에 한번 들어가라고 한 링크에 들어가면

잔여백신 지도를 움직이면 지원하지 않는 환경이라는 팝업이 나옵니다.

왜 그런건지 알 수 있을가요?

**Comment by melona-sudo** [comment]
저는 크롬으로 했을 때 정상적으로 움직이는게 가능했어요.

신청내역, 예약안내, 목록보기를 클릭했을 땐 지원하지 않는 환경이라는 파업창이 떴습니다.

**Comment by hyunjinnnn** [comment]
> 저는 크롬으로 했을 때 정상적으로 움직이는게 가능했어요.
> 
> 신청내역, 예약안내, 목록보기를 클릭했을 땐 지원하지 않는 환경이라는 파업창이 떴습니다.


움직이는건 가능한데 내역 예약안내 뭔가 버튼을 누르면 지원하지 않는 환경이라는 팝업이 나오는데

정상적인건가요??

**Comment by jiho-kang** [comment]
> > 저는 크롬으로 했을 때 정상적으로 움직이는게 가능했어요.
> > 신청내역, 예약안내, 목록보기를 클릭했을 땐 지원하지 않는 환경이라는 파업창이 떴습니다.
> 
> 움직이는건 가능한데 내역 예약안내 뭔가 버튼을 누르면 지원하지 않는 환경이라는 팝업이 나오는데
> 
> 정상적인건가요??

저도 같은 증상입니다.

**Comment by dokdo2013** [comment]
1. 지도의 확대 수준에 따라 그런 알럿창을 띄우는 것 같습니다. 모바일 카카오톡에서 잔여백신 지도를 축소해보면 일정 범위 이상으로 축소가 되지 않습니다. 반면 PC에서 열었을 때에는 그런 제한이 없이 축소가 가능합니다. 이 때 일정 범위 이상으로 축소를 하게 되면 알럿창이 뜹니다.
2. 지도 외에 신청내역, 예약안내, 목록보기 등의 페이지로는 접속되지 않는게 정상입니다. 그런 알림이 뜨더라도 예약은 원활하게 이뤄지니 안심하셔도 됩니다.

**Comment by melona-sudo** [comment]
해당 파업창이 떠도 정상적으로 예약 가능합니다.

오늘도 백신예약 문제 없이 이뤄졌습니다.

**Comment by hyunjinnnn** [comment]
감사합니다.
원래 그런거군요...
