### ISSUE TITLE
실행 도중 Timeout Error 문구 출력

### ISSUE THREAD

**Issue by melonanet** [SJang1/korea-covid-19-remaining-vaccine-macro#818]
오늘 오후에  "API 버전에 변동이 생겨서 업데이트했습니다"를 보고 다운로드 한 파일에서 나타났습니다. 8월 2일에 다운로드 한 파일을 실행하여 예약했을 땐 해당 문구가 발견되지 않았습니다.

정상적으로 실행되다가 아래의 문구가 뜨는 나타났습니다. 문구가 나타난 것 말고는 멈추거나 하는 반응은 없었으나 실행시킨 시간이 어느 정도 흘러가면 자주 보였습니다.

Timeout Error :  HTTPSConnectionPool(host='vaccine-map.kakao.com', port=443): Read timed out. (read timeout=5)

*해당 문구가 백신 예약 되기 전에도 떴지만 백신예약 과정 중 오류가 생겨 정지가 되진 않고 정상적으로 작동하긴 했습니다.

**Comment by MPThLee** [comment]
떠도 넘어가는게 정상입니다.
