### ISSUE TITLE
chrome 브라우저에서 카카오에 제대로 로그인 되어있는데 확인해달라고 뜸

### ISSUE THREAD

**Issue by jiho-kang** [SJang1/korea-covid-19-remaining-vaccine-macro#819]
chorme 브라우저도 로그인, 카카오 계정 로그인 페이지에도 로그인, 로그인 시 주의사항에 적힌 내용 모두 완료 이후 프로그램 실행하면 아래와 같이 나옵니다.

사용자 정보를 불러오는데 실패하였습니다.
Chrome 브라우저에서 카카오에 제대로 로그인되어있는지 확인해주세요.
로그인이 되어 있는데도 안된다면, 카카오톡에 들어가서 잔여백신 알림 신청을 한번 해보세요. 정보제공 동의가 나온다면 동의  후 다시 시도해주세요.

크롬을 삭제하고 다시 깔았는데도 위와 같이 나오네요. 뭐가 문제일까요?

참고로 아직 지도의 좌표가 어디에 쓰이는지 모르는 상태입니다.

**Comment by SJang1** [comment]
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/issues/82
