### ISSUE TITLE
크롬 브라우저로 카카오 로그인 시 주의사항

### ISSUE THREAD

**Issue by SJang1** [SJang1/korea-covid-19-remaining-vaccine-macro#82]
- 크롬 브라우저 설정에서 **모든 쿠키 허용** 을 해주셔야 합니다.
- **시크릿 모드** 에서 로그인하시면 **안됩니다.**
- 응답형 디자인 모드 (모바일로 보기 모드)를 **꺼 주시고** 로그인을 해주셔야 합니다. (개발자도구에 익숙하지 않으신 분들은 문제가 없습니다.)
- User-Agent를 건드리는 확장 프로그램이 있는 경우 꺼주셔야 합니다.
- Chrome의 프로파일이 기본 프로파일이어야 합니다.
- **로그인 상태 유지**를 체크해주세요.
- 로그인 이후 [이 페이지](https://vaccine-map.kakao.com/map2?v=1)에 한번 이상 접근해야합니다.

**Comment by hiskyholic** [comment]
모든 쿠키 허용, 일반모드, 개발자도구 건드리지 않고 모바일보기 아닌 상태인데도 불구하고 아까와 동일한 현상이 발생합니다.
무엇이 문제일까요...

**Comment by SJang1** [comment]
@hiskyholic 사용중인 환경을 알 수 있을까요? (OS, 크롬브라우저 버전 등)

**Comment by hiskyholic** [comment]
@SJang1 OS는 windows 10 education, 크롬 브라우저 버전은 92.0.4515.107 입니다

**Comment by SJang1** [comment]
@hiskyholic 혹시 크롬 확장프로그램 중 Header 정보를 건드리는 확장프로그램이 있으신가요? (User-Agent Switcher 등), 있으시면 비활성화 후 다시 시도해보시겠어요?

**Comment by dlddnd** [comment]
@SJang1 윈7, 크롬 92.0.4515.107 // 모든확장프로그램 비활성화하고 모든쿠키허용 인데 동일 오류 발생합니다...

**Comment by hiskyholic** [comment]
@SJang1 
![image](https://user-images.githubusercontent.com/75426988/126896441-fae21da2-3627-4d32-954c-d200001fbe7b.png)
 현재 확장프로그램 이 상태입니다

**Comment by SJang1** [comment]
@dlddnd Windows 7에서는 지원되지 않을 수 있습니다. 윈도우10 이상으로 업데이트 후 다시 시도해주세요..

**Comment by dlddnd** [comment]
@SJang1 1.06은 잘 작동하였는데 1.07은 안될수도 있는건가용?
                exe말고 파이썬으로 실행했습니다

**Comment by saltedpretzel** [comment]
window 10, 크롬은  92.0.4515.107(공식 빌드) (64비트) 인데 똑같은 현상 발생하네요.

**Comment by SJang1** [comment]
@dlddnd 네. 안될 수 있습니다..
@hiskyholic @saltedpretzel 원인좀 더 찾아보고 오겠습니다 죄송합니다(...)

**Comment by SJang1** [comment]
@hiskyholic @saltedpretzel 혹시 프로파일이 기본 프로파일이 아니지는 않으신지요?

**Comment by hiskyholic** [comment]
@SJang1 카카오계정 프로필 말씀이신가요?

**Comment by hiskyholic** [comment]
@SJang1 현재 설정창에서 로그인되어있는 계정은 개인구글계정, 학교구글계정 두개이며 현재는 개인구글계정으로 설정되어있습니다.

**Comment by SJang1** [comment]
@hiskyholic 구글 계정 로그인된 프로필말고 크롬의 프로파일을 묻는 내용입니다. 
주소창에 `chrome://version` 치고 들어가셔서 `프로필 경로` 부분을 알려주실 수 있으신가요?

**Comment by saltedpretzel** [comment]
@SJang1 Default로 되어있습니다.

**Comment by hiskyholic** [comment]
@SJang1 C:\Users\USER\AppData\Local\Google\Chrome\User Data\Default 입니다

**Comment by jayjay9212** [comment]
저도 어떠한 방법을 써도 사용자 정보 불러오는데 실패했다고 뜨네요..

**Comment by SJang1** [comment]
C:\Users\USER\AppData\Local\Google\Chrome\User Data\ 에서 Default 폴더를 지우거나 다른 이름으로 바꾸고 크롬을 재실행해보시겠어요?
크롬의 유저 데이터는 모두 없어지고 새 크롬 설정같은게 뜰건데 한번 이 방식으로 해보세요

**Comment by jayjay9212** [comment]
> C:\Users\USER\AppData\Local\Google\Chrome\User Data\ 에서 Default 폴더를 지우거나 다른 이름으로 바꾸고 크롬을 재실행해보시겠어요?
> **크롬의 유저 데이터는 모두 없어지고 (중요)** 새 크롬 설정같은게 뜰건데 한번 이 방식으로 해보세요

이렇게 해도 안되네요..ㅠㅠ

**Comment by hj1n** [comment]
크롬에서 **'자동로그인 유지'** 체크한 후, 실행 2번째부터 작동이 잘 되네요.

**Comment by hiskyholic** [comment]
@SJang1 정상적으로 작동합니다. 감사합니다!

**Comment by dlddnd** [comment]
@SJang1 Default폴더 백업 후 시도하려는데 혹시 백업 후 복원하면 다시 기존 데이터 복원되나요??

**Comment by SJang1** [comment]
> @SJang1 Default폴더 백업 후 시도해 보려는데 혹시 백업 후 복원하면 다시 기존 데이터 복원가능한가용??

넹

**Comment by jayjay9212** [comment]
> > @SJang1 Default폴더 백업 후 시도해 보려는데 혹시 백업 후 복원하면 다시 기존 데이터 복원가능한가용??
> 
> 넹

다시 해서 작동 되는거 확인했습니다! 감사합니다
혹시 이것도 여러개 켜둬야 더 효과가 있는걸까요? 
그리고 혹시 예약 실패 되도 종료가 아니라 다시 알아서 작동하는 시스템으로 바뀐건가요?

**Comment by SJang1** [comment]
> 혹시 이것도 여러개 켜둬야 더 효과가 있는걸까요?
> 그리고 혹시 예약 실패 되도 종료가 아니라 다시 알아서 작동하는 시스템으로 바뀐건가요?

하나만 켜두시면 되며, 예약을 성공하거나 의도치 않은 오류가 발생하기 전까지는 예약이 실패되어도 알아서 계속 작동합니다.

**Comment by jayjay9212** [comment]
> > 혹시 이것도 여러개 켜둬야 더 효과가 있는걸까요?
> > 그리고 혹시 예약 실패 되도 종료가 아니라 다시 알아서 작동하는 시스템으로 바뀐건가요?
> 
> 하나만 켜두시면 되며, 예약을 성공하거나 의도치 않은 오류가 발생하기 전까지는 예약이 실패되어도 알아서 계속 작동합니다.

넵 감사합니다!!

**Comment by chw970411** [comment]
안녕하세요 개발자님!
맥북에서 시도해보는중인데,
맨처음에 올려주신건 파이썬으로 실행이 잘되었습니다.

근데 이번에 올려주신걸 하려고 하면 파이썬 오류로 image not found가 계속 뜨는데 이부분은 어떻게 해야할까요?

**Comment by SJang1** [comment]
@chw970411 
새 이슈로 자세한 설명과 함께 다시 올려주시기 바랍니다.

**Comment by dlddnd** [comment]
저는 위 모든 방법 써봐도 안되네요ㅠㅠ 빵빠레소리를 듣고 싶지만 그냥 1.06을 써야겠어요
@SJang1 감사합니다

**Comment by dlddnd** [comment]
@SJang1 1.0.10 버전에서 해당 오류 더이상 발생하지 않습니다!

자동화버전부터는 open_delay가 없던데 0으로 자동설정인가요?

**Comment by SJang1** [comment]
@dlddnd 0.1초 단위로 6번 예약 시도합니다. Off-Topic, 버그 아닌 내용은 여기에 올리지 말아주세요.

**Comment by SJang1** [comment]
관련되어서 문제가 있으면 새 Issue를, 문제가 없는 질문은 Discussions 탭을 이용해주세요.

Off-Topic 내용을 많이 올려서 이 이슈는 Lock하겠습니다.
