### ISSUE TITLE
config.ini에 필요한 값이 없는 경우 오류발생

### ISSUE THREAD

**Issue by SJang1** [SJang1/korea-covid-19-remaining-vaccine-macro#824]
`config.ini`에 필요한 값이 없으면 기존 정보로 진행 시 오류가 발생합니다.

fix방법 : 사전에 `config.ini`에 필요한 값이 모두 있는지 확인 후 있는 경우에만 기존 정보 진행여부 묻기

**Comment by jinh0** [comment]
#792 이 이 문제를 해결합니다.

**Comment by jinh0** [comment]
Update: #850 가 #792 conflict 문제 해결합니다.
