### ISSUE TITLE
전반적인 속도향상 필요

### ISSUE THREAD

**Issue by SJang1** [SJang1/korea-covid-19-remaining-vaccine-macro#829]
코드의 리팩토링 등을 통해 전반적인 속도의 향상이 필요합니다.
물론 속도를 올리면 전반적으로 예약이 좀 더 어려워지겠지만, 이 매크로의 존재 이유가 좀 더 빠르게 잔여백신을 예약하자는 목적이니, 속도향상이 꽤나 중요한 과제로 필요합니다.

p.s.) 가능성은 매우 낮지만 동시에 두 곳 이상의 병원에서 잔여백신이 발생한 경우, 해당 병원 모두에 예약시도를 비동기로 즉시 진행하는 것이 필요할 듯 합니다.

**Comment by jil8885** [comment]
비동기로 진행이 가능하지만 짧은 시간 동안 여러 요청이 들어갈 경우 계정 차단의 위험성이 있고 multiprocessing pool 을 생성하는 시간이 있어 for 문을 사용하는 것 대비 큰 속도 향상이 있진 않을 것 같습니다. 대안으로는 백신의 수가 많은 병원으로 sort하여 많은 병원부터 request 하는 것이 좀 더 높은 가능성을 가지지 않을까 생각합니다.

**Comment by Queue-ri** [comment]
@jil8885 sort는 38ff1547110c24896c467f66039c8bee258242f6 커밋으로 적용된 것 같습니다.

저도 성능 향상에 비동기까지는 생각을 안해봤는데.. 드물긴 해도 잔여 병원이 다수일 경우엔 단시간에 많은 request가 이루어져서 위험할 것 같습니다.

**Comment by KibongChoi** [comment]
백신 수가 많은 상위 3 개 병원에 대해서 async io annotation 으로 호출하면 되지 않을 까 싶은데요. 
카카오에서 request 제한을 얼만큼 할지 모르겠지만,,,

**Comment by nanpuhaha** [comment]
@SJang1 성능 향상이 필요하다고 생각한 이유가 있을까요?

**Comment by SJang1** [comment]
> 성능 향상이 필요하다고 생각한 이유가 있을까요?

사실 간단합니다. 지금의 프로그램이 사용자 인터페이스를 너무 추구했다보니 print하는데에만 시간낭비를 많이 하고 실제 예약까지는 약간 시간이 오래 걸린다고 느껴지고 있기 때문입니다.. 또한, 자동화+예약의 특성상 좀 더 빠르게 시도해야 예약을 할 수 있을 가능성이 높아지는 것도 있고요.

**Comment by JiHunBae** [comment]
사용자 인터페이스를 위해 출력문을 사용하는 것에 대한 시도는 좋았다고 생각합니다. 병원 목록을 보여주어 코드의 구성을 모르는 단순 사용자들에게 잘 동작함을 알리거나 디버깅 용도로  활용할 수 있는 것은 저는 긍정적으로 평가합니다. 그러나 역시 print문은 언제나 함수 실행에 대한 오버헤드가 큰 편에 속합니다. 이 부분을 해결하기 위해서 멀티프로세싱을 적용하여 사용자 정보를 입력받는 부분이 정상적으로 끝난 이후, fork를 진행해 병원 목록을 print해주는 프로세스를 별도로 생성하는 것이 좋지 않을까 생각합니다. 요약하면 아래와 같습니다.

1) 예약 프로세스 - 기존 코드에서 병원 목록을 출력하는 print문을 제거하고 시스템 시간만 출력(매번 또는 count값 활용)하여 프로세스 동작 여부 확인할 수 있게함. 해당 프로세스는 잔여백신이 있으면 예약을 하는 임무만 부여.

2) 사용자 편의 제공(?) 프로세스 - 약 10초 주기로 현재 검색하고 있는 병원의 목록을 업데이트하여 사용자에게 보여줌. (10초 정도마다 한 번 API를 호출하면 계정을 위험하게 하지는 않을 것이라 판단합니다.)

또한 코드에 time.sleep()이 있는데, 이 부분은 삭제해도 계정이 위험해지지 않았습니다. time.sleep()을 없애고 진행했을 때, find_vaccine()을 1초에 최소 3번, 최대 6번 호출하는 것을 확인하였습니다. 현재 예약하는 시간을 단축할 수 있는 가장 간단한 방법은 해당 프로세스 안에 존재하는 print문을 최대한 없애는 것입니다. 그 이외의 최적화는 추후에 생각해도 괜찮을 것 같습니다.

**Comment by paisano55** [comment]
이 코드가 굉장히 많은 사람들에게 공개된 이상 sleep은 최소한의 안전장치로 필요할 것 같습니다.
이미 1개로도 충분하다고 많이 말씀을 드렸는데도 꼭 몇 개씩 켜놓으시는 분들이 있습니다. 5개인가 켜놓으셨던 분의 경우 예약 시도 함수가 일시적으로 너무 많이 request를 하여 밴 되셨다고 보았습니다.

다만 sleep 시간을 유동적으로 조절할 수 있다면 괜찮을 것 같습니다. 동일한 컴퓨터에서도 백신 탐색 회당 딜레이가 확연히 차이가 나는것을 보아, 아마 사용자의 네트워크 상태에 따라서 차이가 날 듯 합니다. 최근 몇십회의 request 소요 시간을 보고 sleep의 간격을 조절할 수 있다면, 나쁘지 않을듯 합니다.

**Comment by Queue-ri** [comment]
@JiHunBae `time.sleep()` 을 줄이는 것이 간단한 속도 향상 방법은 맞습니다만, 현재 이 repo는 외부에 잘 알려져 있고 아예 어디서 좌표를 찍고 오는 듯 합니다.개발자님이 빌드 파일까지 release 하시기 때문에 일반 사용자도 쉽게 접근할 수 있는 상황에서, sleep 없는 빌드가 올라가면 카카오 서버에 이전보다 더 많은 부하가 가해지게 될 겁니다. 정도가 심해지면 카카오에서 어떤 대응을 할 지 모르고요. 지금도 Discussion 보면 성공하시는 분들이 계시던데, 그럼 그대로 두어도 괜찮지 않나 싶습니다.

**Comment by SJang1** [comment]
너무 빠르게 시도하면 예약을 실패한다는 후기가 올라와, 해당 이슈는 더이상 필요 없다 판단됩니다. 감사합니다 :)
