### ISSUE TITLE
업데이트된 버전 다운받았을 때 실행이 안됩니다.

### ISSUE THREAD

**Issue by Yeonwoo0801** [SJang1/korea-covid-19-remaining-vaccine-macro#843]
어제 release에 업데이트 된 vaccine-run-kakao-windows.exe 윈도우 버전을

실행하면 Assertion failed; bool_res, file static_src\OnefileBootstrap.c, line 781

라는 문구가 뜨면서 꺼집니다.

이 경우에는 어떤 오류가 발생한건가요?

**Comment by MPThLee** [comment]
일부 백신프로그램의 경우에 발생한다고 알려진 문제점입니다. 한번 백신을 끄고 시도해보시길 바랍니다. 
#725
