### ISSUE TITLE
에러가 계속 뜹니다...버전은 최신버전인데...

### ISSUE THREAD

**Issue by JamesJeongM** [SJang1/korea-covid-19-remaining-vaccine-macro#855]
다음과 같은 에러가 자꾸 뜨네요..
Assertion failed : bool_res, file static_src￦Onefilebootstrap.c, line 781

**Comment by SJang1** [comment]
일부 백신프로그램의 경우에 발생한다고 알려진 문제점입니다. 한번 백신을 끄고 시도해보시길 바랍니다.
#725
