### ISSUE TITLE
크롬 브라우저로 카카오 로그인 시 주의사항

### ISSUE THREAD

**Issue by Krnmc714** [SJang1/korea-covid-19-remaining-vaccine-macro#868]
안녕하세요 제가 지금 #82 같은 문제가 생기는데. #82에 있는 방법 다 해봤는데 아직도 안되고 있었어 문희 드립니다. 

혹시 "로그인 상태 유지를 체크해주세요." 말씀 하시는게 카카오 로그인 할때 맞나요? 그리고 크롬 삭재 하고 다시 시작 하면 개인 구글로 로그인 하나요?

죄송해요 제가 쿄포 라서 한글은 잘 하는 편이 아니라서... ㅠㅠ 감사합니다!

**Comment by SJang1** [comment]
> 혹시 "로그인 상태 유지를 체크해주세요." 말씀 하시는게 카카오 로그인 할때 맞나요

네

> 크롬 삭재 하고 다시 시작 하면 개인 구글로 로그인 하나요?

아니요
