### ISSUE TITLE
try_reservation 함수가 호출되지 않음

### ISSUE THREAD

**Issue by SJang1** [SJang1/korea-covid-19-remaining-vaccine-macro#884]
Branch : main
try_reservation 함수가 호출되지 않는 것이 확인되었습니다.

**Comment by paisano55** [comment]
제가 예약쪽 코드는 처음 살펴보았는데요..호출이 안 된다는것이 정확히 어떤 말씀이신지요?
find_vaccine의 while문을 통과하기만 하면 try_reservation 호출 부분까지는 무조건 도달하지 않나요?

**Comment by SJang1** [comment]
분명히 그래야하는데........ 이상하게 예약시도 자체가 안됩니다.......... 🤔

**Comment by paisano55** [comment]
try_reservation에 문제가 있는거 아닐까요?
API가 바뀌어서 for문 내부 if문에서 안 걸리고 그냥 넘어가버린다던가..
그런데 어제도 잘 쓰시던 분들이 많았는데 요상하네용

**Comment by SJang1** [comment]
api는 체크해봤는데 달라진 것 없습니다

**Comment by paisano55** [comment]
그러면  find_vaccine의 while 문을 빠져나와서 ~에서 백신을 ~개 발견했습니다 부분이 print까지는 되는데, 이후에 try_reservation 까지 도달하지 못 하고 먹통이 된다는 것인가요?

**Comment by SJang1** [comment]
그렇습니다. n개 발견까지는 잘 되는데 이후에 먹통이 아니라 그냥 예약시도를 하지 않고 다시 백신검색절차로 돌아옵니다.

**Comment by JINHYUKJEONG** [comment]
저는 Queue-ri님의 포크버전을 사용중이였는데 확실히 발견까지만 출력되고 다시 검색만했었네요

**Comment by JINHYUKJEONG** [comment]
제가보기에는 try_reservation안의  requests요청중에 문제가 발생해서 response가 비어있어서 response_json이 빈값이기때문에 for문자체가 실행하지 않는것같습니다.

**Comment by SJang1** [comment]
그런거면 for 전에 있는 json.loads(response.text) 부분에서 문제가 발생했어야 했을텐데 에러 뜨는것도 없었고요.. 흐음

**Comment by paisano55** [comment]
try_reservation 안에 print를 몇 개 두고 어디까지 넘어가나만 찍어봐도 대충 파악가능할듯 합니다.
낼 예약하면서 함 해봐야겠네요

**Comment by dnsdudwk35** [comment]
어제 그런 경우가 있었는데 알고보니 지자체 자율접종 대상자였습니다. 사전예약은 안 한 상태였고요.
그런 사람인 경우에는 User Check 단계에서 걸러내지 못하는 듯 합니다.
저도 시간이 없어서 함수마다 찍어보진 못했는데 이런 외부의 요인도 있었습니다.
다른 분들은 해당 릴리즈도 된다면 그런 부분도 생각해야 할 듯 합니다.

**Comment by SJang1** [comment]
지자체 접종 대상자 등 이미 다른 예약이 되어있는경우 예약시도 시 멈췄어야 합니다.
계속 돌아갔단거는 예약시도가 안되었단 것이고..

**Comment by dnsdudwk35** [comment]
지자체 접종 대상자인데 전산 오류로 등록이 늦게 되신 분이었습니다.
예약 시도시 User Check 에서 Filtering 안되더라구요. 실제 사전예약은 안되어있고, 사전예약 가능한 상태로 확인했습니다.
혹여나 이런 케이스일 수 있어 Comment 드립니다만, 가능성이 높진 않아 보입니다.

**Comment by SJang1** [comment]
네. 그런 경우 프로그램 작동이 중단되었어야 합니다.

중단없이 예약시도했을때 나오는 문구 없이 계속 검색하는곳으로 다시 돌아온걸 보면 확실히 예약시도 자체가 안되었던걸로 보입니다.

**Comment by Queue-ri** [comment]
> 저는 Queue-ri님의 포크버전을 사용중이였는데 확실히 발견까지만 출력되고 다시 검색만했었네요

해당 repo 이슈로 자세한 설명 부탁드립니다.

제껀 예약 시도 후 출력하는 형식이라 출력이 되었다면 request가 이미 이뤄지고 response도 받은 것입니다.

response 내용이 이상해도 else에 걸려서 출력되었어야 합니다.

**Comment by SJang1** [comment]
테스트 환경에서 시도했을땐 또 제대로 돌아가네요... What the.....?

**Comment by Queue-ri** [comment]
`try_reservation` 호출 자체가 안되는 문제인가요 아님 호출은 되는데 request 쪽 문제인가요?

제목 보고 전자라고 생각했는데 내용은 후자같아서..

**Comment by SJang1** [comment]
전자 문제로 파악중이었으나............ 테스트 환경에서는 후자일 거라는 확인 후 지금 너무 `?????????????????` 상태에 와있습니다.

**Comment by paisano55** [comment]
현재 깃 최신 버전으로 테스트 해본 결과 잘 되었습니다

**Comment by SJang1** [comment]
감사합니다. 진짜 알 수 없는 예외상황에서 발생한 문제같네요.. 🤔

**Comment by SJang1** [comment]
일단 정상작동한다고 하니 이 이슈는 Close하겠습니다.

**Comment by dudwo1128** [comment]
try_reservation 내에서 response_json을 프린트해보니 {'error' : 'error occurred'}가 뜨는데, 혹시 request가 제대로 작동하지 못한건가요? 아니면 그냥 서버 문제로 보이시나요?

**Comment by SJang1** [comment]
> try_reservation 내에서 response_json을 프린트해보니 {'error' : 'error occurred'}가 뜨는데, 혹시 request가 제대로 작동하지 못한건가요? 아니면 그냥 서버 문제로 보이시나요?

카카오계정 로그인이 풀린겁니다.

**Comment by dudwo1128** [comment]
크롬으로 확인해보니,
https://vaccine.kakao.com/api/v1/user 에선 제가 알림 신청한 병원 리스트가 뜨는데,
https://vaccine.kakao.com/api/v2/reservation 에서 {"error":"error occurred"} 에러가 쓰면 로그인이 풀린건가요?

**Comment by SJang1** [comment]
> 크롬으로 확인해보니,
> https://vaccine.kakao.com/api/v1/user 에선 제가 알림 신청한 병원 리스트가 뜨는데,
> https://vaccine.kakao.com/api/v2/reservation 에서 {"error":"error occurred"} 에러가 쓰면 로그인이 풀린건가요?

reservation 페이지는 크롬으로 링크 들어가서 접근이 불가하며, 링크를 쳐서 들어가는 경우 해당 오류는 정상입니다.

**Comment by dudwo1128** [comment]
자꾸 번거롭게 해드려서 죄송합니다만..
그럼 카카오 로그인을 크롬으로 새로 해야하는건가요? 아니면 단순히 코드를 재시작하면 될까요?
