### ISSUE TITLE
framework not loaded while loading pygame

### ISSUE THREAD

**Issue by SJang1** [SJang1/korea-covid-19-remaining-vaccine-macro#90]
### Discussed in https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/discussions/86

<div type='discussions-op-text'>

<sup>Originally posted by **chw970411** July 25, 2021</sup>
안녕하세요, 
현재 맥북 사용중인데요 지난번 버전은 됐으나 이번프로그램은 실행이 안되어 질문드립니다! 오류 첨부드립니다!
감사합니다.
![스크린샷 2021-07-25 오후 11 26 03](https://user-images.githubusercontent.com/87938110/126902657-dea19150-678a-4e61-aa2b-4fb151cd90d7.png)
</div>

Binary로도 실행이 안됨.

**Comment by Jayyyy-04** [comment]
안녕하세요 좋은 아침입니다 :)
[https://files.pythonhosted.org/packages/d0/f9/8463d50b0369921f9b2ff7c1bf671a683e0a9a3a6c048edf3cbec85b8545/pygame-2.0.1-cp36-cp36m-macosx_10_9_intel.whl](url)
Mac OS Pythone3.6에 대응하는 pygame wheel파일 입니다. Module 수동으로 재설치하여도 같은 현상일지 확인해 볼 필요가 있어보이네요

**Comment by SJang1** [comment]
@chw970411 확인 부탁드립니다 :)
제 환경에서는 문제가 발행하지 않고 있어서 확인을 해주셔야 할 것 같습니다.
