### ISSUE TITLE
[QUESTION] 예약없이 빵빠레가 아닌 소리와 함께 오류라고 떠요!

### ISSUE THREAD

**Issue by oIlydaisy** [SJang1/korea-covid-19-remaining-vaccine-macro#921]
{"code":"ALREADY_REGISTERED","desc":"알수없는 이유로 예약이 불가합니다.\n자세한 내용은 질병관리청으로 문의해주세요."

라고 쭉 뜨는데 이건 해결방법이 있을까요?

**Comment by sanvit** [comment]
카카오 JS파일 뜯어보니까 이렇게 나오네요
백신접종 예약내역이 있거나 이미 접종을 하신 경우 잔여백신 접종 신청이 불가합니다.

**Comment by oIlydaisy** [comment]
> 카카오 JS파일 뜯어보니까 이렇게 나오네요
> 백신접종 예약내역이 있거나 이미 접종을 하신 경우 잔여백신 접종 신청이 불가합니다.

둘 다 아닌데 이상하네요ㅠㅠ 답변 감사합니다

**Comment by sanvit** [comment]
혹시 사전예약을 하셨거나 잔여백신 예약이 됐는데 모르고 계시는거 아닐까요? 카카오톡 한번 확인해보세요. 그리고 지금 돌아가는 계정이 본인 계정이 맞는지도 다시한번 확인해보시구요

**Comment by paisano55** [comment]
ALREADY RESERVED면 아마 사전예약이 되있는것 같습니다

**Comment by SJang1** [comment]
이미 사전예약이 되어있는 경우에 발생합니다..
