### ISSUE TITLE
[CRITICAL] 백신 종류 검증에 대한 개선 필요 - AZ만 있어도 계속 예약시도중

### ISSUE THREAD

**Issue by akakakakak1** [SJang1/korea-covid-19-remaining-vaccine-macro#942]
확인 한번 부탁드려요! 
화이자 선택 했는데 계쏙 다른 백신 시도하네요...

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 build 19043.1110, MacOS 12 21A5294g]
 - Program Version [e.g. 1.0.18, a9e7d446ad14b4c8ac7d067474c005a45a01eb9e]

**Additional context**

**Comment by luftaquila** [comment]
request.py의 find_vaccine() 함수에서 백신을 찾았을 때 found 객체에 leftCounts만 있고 백신 종류가 뭔지는 없어서 생기는 문제 같습니다.

해당 기관에 무슨 백신이 있는지 확인하려면 vaccine_type이 `ANY`일 때처럼 request를 보내 확인해야 하는데 요청을 주고받는 시간만큼 느려지기 때문에 남은 백신 종류는 확인하지 않고 그냥 예약 시도하는 걸로 보입니다.

**Comment by luftaquila** [comment]
다만 오늘 경기권에서 AZ가 엄청나게 쏟아져 나오는데, 프로그램은 백신 종류에 관계없이 총 잔여 개수가 가장 많은 기관 하나에 시도합니다. 어느 기관에 화이자가 하나 있더라도 다른 기관에 AZ 개수가 더 많아버리면 무시되기 때문에 백신 코드 지정 옵션이 의미가 없어 보입니다.

**Comment by j0seo** [comment]
카카오 구조상 전체 맵에서 백신별 잔여량이 나오지 않고 각 병원마다 리퀘스트를 해야 나오게 된다면 네이버에서 조회 후 예약은 카카오에서 하는 방법으로 선회하면 어떨까요? 네이버는 현재 전체 맵에서 백신별 수량이 나오고 있습니다.

**Comment by luftaquila** [comment]
> 카카오 구조상 전체 맵에서 백신별 잔여량이 나오지 않고 각 병원마다 리퀘스트를 해야 나오게 된다면 네이버에서 조회 후 예약은 카카오에서 하는 방법으로 선회하면 어떨까요? 네이버는 현재 전체 맵에서 백신별 수량이 나오고 있습니다.

방금 잠깐 봤는데 두 서비스에서 기관 코드는 같네요. 가능할 것 같습니다.

**Comment by SJang1** [comment]
네이버는 과도한 많은 요청 시에 백신 발생 시 모든 병원 데이터를 보내주지 않는 내용의 패치가 되어있었습니다. = 요청을 자주 할 수 없습니다.

**Comment by SJang1** [comment]
ANY에서 하는 듯이 잔여백신 발생 시에 해당 병원에 우선 무슨 백신이 남아있는지 확인하고 남은게 사용자가 원하는 백신이 아니면 다음 병원으로 같은 절차를 반복하는 패치를 하는것도 나쁘지 않아 보입니다. (기존 아이디어였는데 더 빠른 예약을 원하셔셔 아이디어 폐기했었습니다)

**Comment by SJang1** [comment]
더이상 `ANY`옵션을 유지하기도 어렵겠네요. `ANY`로 하게 된다면 무슨 백신 중에 아무거나? 를 물어봐서 그 백신이 남아있는지 확인이 필요해 보입니다.

**Comment by luftaquila** [comment]
> 네이버는 과도한 많은 요청 시에 백신 발생 시 모든 병원 데이터를 보내주지 않는 내용의 패치가 되어있었습니다. = 요청을 자주 할 수 없습니다.

이런 게 있었군요.. 만들어보려고 했는데 빠르게 포기했습니다.
말씀하신 각 기관별로 다시 가지고 있는 백신이 뭔지 확인하는 방법이 제일 좋아 보이네요.

`ANY` 옵션에 관해서는 gps 좌표 파싱하는 것처럼 희망하는 백신 목록을 전부 입력하고 `,`로 파싱해도 괜찮을 것 같습니다.

**Comment by sudorphine** [comment]
> ANY에서 하는 듯이 잔여백신 발생 시에 해당 병원에 우선 무슨 백신이 남아있는지 확인하고 남은게 사용자가 원하는 백신이 아니면 다음 병원으로 같은 절차를 반복하는 패치를 하는것도 나쁘지 않아 보입니다. (기존 아이디어였는데 더 빠른 예약을 원하셔셔 아이디어 폐기했었습니다)

예약이 실패됐을 때 뒤에 남아있는 병원을 마저 스캔하도록 하는 방식은 불가능 한가요?

**Comment by SJang1** [comment]
수정 가능하신 분 있으면 PR 부탁드립니다. 다른 일때문에 좀 바빠서 제가 지금 직접 수정하기엔 약간의 어려움이 있네요.

**Comment by j0seo** [comment]
잔여백신이 존재하는 병원을 모두 조회하여 정보를 불러오니 한번 검색하는 딜레이가 상당히 길어지게 되네요
이에 직전 검색기록과 대조하여 잔여백신 갯수가 변하지 않은 병원의 경우 백신종류 조회를 제외시키니 성능이 매우 좋아집니다.

**Comment by SJang1** [comment]
Release되었습니다! :)
