### ISSUE TITLE
[QUESTION] 다른 계정으로 로그인 실패, 같은 병원 계속 등장(에러같음)

### ISSUE THREAD

**Issue by dannyljw** [SJang1/korea-covid-19-remaining-vaccine-macro#958]
안녕하세요 한명 성공하고(user A) 나서 다른 사람 카카오 계정(user B) 으로 진행하려고, 크롬에서 다른 사람 계정으로(user B) 로그인을 하고 프로그램을 실행하는데 (MAC) 계속 기존에 저장되어있던 카카오 계정 (user A ) 은 이미 백신 접종을 받았습니다! 라고 뜨는데요, 혹시 저 말고 다른 사람 카카오 계정으로 진행하려고 하면 어떤 조치를 취해야될까요? 

또한, 

지인은 윈도우인데, 에러가 나서 그런지 **병원 (경기도~~~로 )에서 잔여백신이 4개 있습니다. 라는 문구가 연속적으로 등장합니다. 

혹시 어떻게 해결 해야되는지 궁금합니다 감사합니다

**Comment by Queue-ri** [comment]
1. 크롬에서 쿠키를 삭제하고 다시 로그인하시면 될 것 같습니다.

2. [이전의 답변](https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/discussions/957)을 참조부탁드립니다.

**Comment by dannyljw** [comment]
크롬에서 쿠키를 다 삭제했는데도 동일한 오류가 나옵니다 ㅠㅠ ㅠ user A 는 이미 접종자 입니다... 라고 뜹니다. 
컴퓨터에서 Chrome을 엽니다.
오른쪽 상단에서 더보기 더보기 다음 설정을 클릭합니다.
'개인정보 및 보안'에서 쿠키 및 기타 사이트 데이터를 클릭합니다.
모든 쿠키 및 사이트 데이터 보기 다음 모두 삭제를 클릭합니다.
모두 삭제를 클릭하여 확인합니다.

절차를 밟았었는데도 안되는 것 같습니다. 다른 사람의 카카오 아이디로 로그인했는데도 말이죠....

**Comment by Hox2ney** [comment]
@dannyljw https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/issues/942 이 현상과 같은 것으로 보입니다.

**Comment by hyunie88** [comment]
READ.MD 에 나와있는 경로로 로그인하시면 
![wqewqe](https://user-images.githubusercontent.com/70103279/128658202-a771ab99-d6df-4fe7-9e81-ef7a9357eb97.PNG)

우측 상단에 로그아웃 버튼이 보입니다. 기존 A계정을 해당 부분에서 로그아웃 하신 후 시도해보세요.

**Comment by mj-yun** [comment]
저도 같은 현상 반복입니다... 맥북은 그전 (user A)가 이미 접종 완료되었습니다!로 뜨고 
다른 윈도우 컴으로 시도하니 같은 병원에서 백신을 @개 발견했습니다! 가 반복해서 뜨네요;;

크롬 재다운 받고 맥북 업데이트도 하고, (user A)계정으로 다시 로그인했다가 로그아웃한 후 (user B)로 다시 로그인해도 (user A)가 접종 완료되었다고 뜨네요..

**Comment by Queue-ri** [comment]
혹시 `cookie.ini` 파일 때문에 그런 것 아닌지요?

**Comment by twinslgs** [comment]
> 혹시 `cookie.ini` 파일 때문에 그런 것 아닌지요? 이 파일을 지우고 다시 시도해보세요.

지워도 똑같이 뜹니다 ㅠㅠ

**Comment by mj-yun** [comment]
오 저는 지우니까 성공했어요. 근데 저번주랑 다르게 윈도우랑 같은 방식(#942) 으로 뜨네요

**Comment by mj-yun** [comment]
오 저는 지우니까 성공했어요. 근데 저번주랑 다르게 윈도우랑 같은 방식(#957) 으로 뜨네요

**Comment by dannyljw** [comment]
> 저도 같은 현상 반복입니다... 맥북은 그전 (user A)가 이미 접종 완료되었습니다!로 뜨고
> 다른 윈도우 컴으로 시도하니 같은 병원에서 백신을 @개 발견했습니다! 가 반복해서 뜨네요;;
> 
> 크롬 재다운 받고 맥북 업데이트도 하고, (user A)계정으로 다시 로그인했다가 로그아웃한 후 (user B)로 다시 로그인해도 (user A)가 접종 완료되었다고 뜨네요..

지금 AZ 가 많이 풀려서 그렇다고 하네요

**Comment by dannyljw** [comment]
> 혹시 `cookie.ini` 파일 때문에 그런 것 아닌지요? 이 파일을 지우고 다시 시도해보세요.

맥으로는 cookie.ini 파일 을 어떻게 찾아서 삭제하는지 모르겠습니다... 저는 파일도 Mac.tar 만 다운받았었는데 혹시 어떻게 진행하나요?

**Comment by SJang1** [comment]
> 맥으로는 cookie.ini 파일 을 어떻게 찾아서 삭제하는지 모르겠습니다... 저는 파일도 Mac.tar 만 다운받았었는데 혹시 어떻게 진행하나요?

Finder에서 Cmd+Shift+G를 누르시고 입력창에 `~/` 입력하셔서 유저 홈 디렉토리로 이동하신 후 cookie.ini 파일을 찾아보세요.

**Comment by joshjlew** [comment]
저도 동일병원이 마감이 되었음에도 계속 나옵니다.
윈도우고 cookie.ini 지우고 해봤는데도 안되네요.
...
김준호의원 에서 백신을 8개 발견했습니다.
주소는 : 서울 영등포구 의사당대로 108 입니다.
VEN00013 으로 예약을 시도합니다.
잔여백신 접종 신청이 선착순 마감되었습니다.
김준호의원 에서 백신을 8개 발견했습니다.
주소는 : 서울 영등포구 의사당대로 108 입니다.
VEN00013 으로 예약을 시도합니다.
잔여백신 접종 신청이 선착순 마감되었습니다.
김준호의원 에서 백신을 8개 발견했습니다.
주소는 : 서울 영등포구 의사당대로 108 입니다.
VEN00013 으로 예약을 시도합니다.
잔여백신 접종 신청이 선착순 마감되었습니다.
김준호의원 에서 백신을 8개 발견했습니다.
주소는 : 서울 영등포구 의사당대로 108 입니다.
VEN00013 으로 예약을 시도합니다.

**Comment by SJang1** [comment]
새로 나온 병원에서 해결완료되었습니다. 새로 받아서 이용해주세요.
