### ISSUE TITLE
[QUESTION] 오늘은 포기해야되겠네요.

### ISSUE THREAD

**Issue by goerhohojo** [SJang1/korea-covid-19-remaining-vaccine-macro#965]
로직상 백신종류와 상관없이 잔여백신 숫자가 많은 병원으로 예약을 진행하는거 같은데.. 

오늘은 AZ 물량이 전체적으로 풀려서 AZ가 많은 병원을 계속 트라이하네요

AZ 물량이 많은 날은 정상적으로 화이잔, 모더나 예약하기 힘들듯하네요 ㅜㅜ

**Comment by SJang1** [comment]
현재 해당 문제점 트래킹중입니다. 오늘은 이용 자제 권고드립니다.
