### ISSUE TITLE
[BUG] 무조건 선착순 마감되었다고 뜨는 문제

### ISSUE THREAD

**Issue by luftaquila** [SJang1/korea-covid-19-remaining-vaccine-macro#980]
**Describe the bug**
백신 예약 API에 파라미터가 전부 제대로 들어갔음에도 선착순 마감되었다고 뜨는 이슈가 있는 것 같습니다.
Chrome에서 개발자 도구의 모바일 에뮬레이션으로 멀쩡히 AZ 남아있는 병원에 예약 시도를 했을 때도 같은 화면이 나오는 걸 보면 서버 문제인 것 같기도 합니다.
아니면 header 부분에 카톡 앱에서만 작동하도록 검증하는 요소가 무언가 추가됐을지도 모르겠네요.

https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/pull/972#issuecomment-895030275

**Screenshots**
![image](https://user-images.githubusercontent.com/17094868/128680214-0caf5494-3798-497d-82c8-f6e5475daa7d.png)

**Comment by SJang1** [comment]
현재 카카오톡 내 잔여백신 앱으로 AZ예약시도해봤을때도 접종가능연령이 아니란게 아니라 마감이라고 뜨는걸 봐서는 일단 지금은 카카오쪽 서버 버그일거같습니다.

**Comment by luftaquila** [comment]
> 현재 카카오톡 내 잔여백신 탭으로 AZ예약시도해봤을때도 접종가능연령이 아니란게 아니라 마감이라고 뜨는걸 봐서는 일단 지금은 카카오쪽 서버 버그일거같습니다.

그런데 또 수정한 코드로 성공한 분들이 계시다니 이상하네요..

**Comment by luftaquila** [comment]
계속 발생하는 이슈지만 예약이 되는 건 확인됐으니 닫겠습니다.
