### ISSUE TITLE
[FR] 예약한 병원에 모두 백신이 없는 경우 별도 안내를 해줬으면 합니다.

### ISSUE THREAD

**Issue by im-on-the-next-level** [SJang1/korea-covid-19-remaining-vaccine-macro#983]
비개발자 친구가 본 프로그램을 쓰는데, 오류가 있는것같다고 해서 확인해 보니까 별도 안내 없이 현재 시간만 주르륵 나오더라구요.

코드를 대략적으로 보니 오류가 아닌, 예약신청한 병원이 모두 문닫거나 남아있는 백신이 없는 경우 별도 안내 없이 시간만 띄우게끔 돼있어 오해를 한것같은데 이부분때문에 프로그램이 잘 돌고있는지 알지 못할 수 있을것같습니다.

![image](https://user-images.githubusercontent.com/12643838/128683317-ce69b4e1-84c6-4812-ac64-69791d394bf6.png)

또한 프로그램 구조상 한번에 여러 병원에서 백신이 오픈된 경우 맨위에 하나만 잡는다는점도 오류가 아닌지 오해하는 경우도 있는것같아 별도의 안내가 되면 좋을듯합니다.
(이건 기존에 말씀 하셨던것들 보니 개선은 힘들듯 보여 간단히 안내만 해줘도 오해가 줄어들것이라 생각합니다.)

저는 파이썬을 평소에 안다뤄서 컨벤션이 무너지는 문제등을 우려하여 PR대신 이슈트래킹만 해놓고 가겠습니다.
고생하시는 개발자분들 감사드립니다.

**Comment by jong950715** [comment]
def pretty_print(json_object):
    for org in json_object["organizations"]:
        if org.get('status') == "CLOSED" or org.get('status') == "EXHAUSTED" or org.get('status') == "UNAVAILABLE":
            continue
        print(f"잔여갯수: {org.get('leftCounts')}\t상태: {org.get('status')}\t기관명: {org.get('orgName')}\t주소: {org.get('address')}")

    if len(json_object["organizations"]) == 0:
        print("범위 내에 잔여 백신이 없습니다. 잔여 백신을 찾고 있습니다.")

**Comment by im-on-the-next-level** [comment]
`pretty_print`라는게 디버깅용 코드인줄 알았는데 파이썬 내장함수같은게 아니었군요 .. 감사합니다
필요한 로직을 정확히 말씀드리면 **범위 내 병원중 `INPUT_YET` 상태인 병원이 단 한개도 없을 경우** 발생하는 문제입니다.

![image](https://user-images.githubusercontent.com/12643838/128797345-0bb1e96f-7263-4be0-a44a-1d4578c4ab0d.png)

제 추측으로는 병원 상태가 `INPUT_YET`이 아닌 상태라 하면, 
병원 영업종료 시간이 끝났다는 의미로 보이는데 시골은 저녁 5~6시만 돼도 범위내 모든 병원이 `CLOSED`상태로 변해버립니다.

@jong950715 님이 작성해주신 코드에서 제가 말씀드린 부분을 첨가하면

``` python
def pretty_print(json_object):
    available_organization_count = 0

    for org in json_object["organizations"]:
        if org.get('status') == "CLOSED" or org.get('status') == "EXHAUSTED" or org.get('status') == "UNAVAILABLE":
            continue
        available_organization_count += 1
        print(f"잔여갯수: {org.get('leftCounts')}\t상태: {org.get('status')}\t기관명: {org.get('orgName')}\t주소: {org.get('address')}")

    if len(json_object["organizations"]) == 0:
        print("범위 내에 검색 가능한 병원이 없습니다. 좌표를 다시 설정해주세요.")
    elif available_organization_count == 0:
        print("범위 내 영업중인 병원이 없습니다. 좌표를 다시 설정해주시거나, 병원 영업시간 내 이용해주세요.")
```

정도로 정리가 될것같습니다.

**Comment by im-on-the-next-level** [comment]
본 주제에는 좀 벗어나는 얘기지만, 백신 예약에 실패했을 경우에 프로그램이 중단되는 내용에 대한 안내가 조금 더 상세하게 써있으면 어떨까싶습니다.

아무생각 없이 ANY찍는 사람 많을것같은데 이런 경우에 나이 어린데 AZ백신이 잡힌 경우에는 그냥 프로그램이 중단되어 버린다는점을 인지하지 못하는 사람들이 꽤 많을것같습니다.

![image](https://user-images.githubusercontent.com/12643838/128799743-8efe7fbf-555f-4716-9c4e-542ccaa728af.png)

README.md에 `예약 시도 후에는 자동 예약 프로그램은 정지됩니다.`라고 적혀있는 부분 밑에 `반드시 본인이 접종 가능한 종류의 백신만을 선택해주세요.` 정도의 안내문구를 추가하는건 어떤가요?

**Comment by SJang1** [comment]
> 아무생각 없이 ANY찍는 사람 많을것같은데 이런 경우에 나이 어린데 AZ백신이 잡힌 경우에는 그냥 프로그램이 중단되어 버린다는점을 인지하지 못하는 사람들이 꽤 많을것같습니다.

현재 발생하고 있는 버그일 뿐입니다. `ANY` 선택값은 없어질 예정이고 현재 PR에서 처리중입니다.
주제에 벗어나는 이야기는 새 이슈를 생성해주셨으면 합니다.

**Comment by SJang1** [comment]
> 아무생각 없이 ANY찍는 사람 많을것같은데 이런 경우에 나이 어린데 AZ백신이 잡힌 경우에는 그냥 프로그램이 중단되어 버린다는점을 인지하지 못하는 사람들이 꽤 많을것같습니다.

현재 발생하고 있는 버그일 뿐입니다. `ANY` 선택값은 없어질 예정이고 현재 PR에서 처리중입니다.
주제에 벗어나는 이야기는 새 이슈를 생성해주셨으면 합니다.

**Comment by im-on-the-next-level** [comment]
아 파악하고 계신 문제였군요 죄송합니다.

개선이 힘든 문제라 생각하여 간단한 안내문구만 추가하였으면 좋겠다는 말씀을 드린거라, 어차피 본 이슈가 안내문구 부재에 대한 내용이니 큰 맥락에서 보면 새 이슈를 뽑기에는 좀 과하다는 생각이었습니다.

감사합니다.

**Comment by SJang1** [comment]
> `pretty_print`라는게 디버깅용 코드인줄 알았는데 파이썬 내장함수같은게 아니었군요 .. 감사합니다
> 필요한 로직을 정확히 말씀드리면 **범위 내 병원중 `INPUT_YET` 상태인 병원이 단 한개도 없을 경우** 발생하는 문제입니다.
> 
> ![image](https://user-images.githubusercontent.com/12643838/128797345-0bb1e96f-7263-4be0-a44a-1d4578c4ab0d.png)
> 
> 제 추측으로는 병원 상태가 `INPUT_YET`이 아닌 상태라 하면,
> 병원 영업종료 시간이 끝났다는 의미로 보이는데 시골은 저녁 5~6시만 돼도 범위내 모든 병원이 `CLOSED`상태로 변해버립니다.
> 
> @jong950715 님이 작성해주신 코드에서 제가 말씀드린 부분을 첨가하면
> 
> ```python
> def pretty_print(json_object):
>     available_organization_count = 0
> 
>     for org in json_object["organizations"]:
>         if org.get('status') == "CLOSED" or org.get('status') == "EXHAUSTED" or org.get('status') == "UNAVAILABLE":
>             continue
>         available_organization_count += 1
>         print(f"잔여갯수: {org.get('leftCounts')}\t상태: {org.get('status')}\t기관명: {org.get('orgName')}\t주소: {org.get('address')}")
> 
>     if len(json_object["organizations"]) == 0:
>         print("범위 내에 검색 가능한 병원이 없습니다. 좌표를 다시 설정해주세요.")
>     elif available_organization_count == 0:
>         print("범위 내 영업중인 병원이 없습니다. 좌표를 다시 설정해주시거나, 병원 영업시간 내 이용해주세요.")
> ```
> 
> 정도로 정리가 될것같습니다.

해당 코드로 업데이트 main에 되었습니다! 감사합니다!
