### ISSUE TITLE
첫번째 좌표를 입력후 엔터를 치면 프로그램이 꺼집니다...[BUG] 

### ISSUE THREAD

**Issue by AJaaaad** [SJang1/korea-covid-19-remaining-vaccine-macro#991]
**Describe the bug**
백신 종류 입력 후, 좌표를 입력하면 프로그램이 자동으로 종료되는데...이거 어떻게 해야 하죠?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 build 19043.1110, MacOS 12 21A5294g]
 - Program Version [e.g. 1.0.18, a9e7d446ad14b4c8ac7d067474c005a45a01eb9e]

**Additional context**

**Comment by seunghwaShin** [comment]
위경도 모두 입력하셨나요? 저도 하나만 입력하니 종료되더라구요

**Comment by max-jang** [comment]
39.1234512, 127.12341234 포맷에 맞춰서 하신건가요?

**Comment by AJaaaad** [comment]
Google 맵으로 좌표 따면, 127.123123, 36.123123 이렇게 6자리로 나오고, 저번주에 되었는데 오늘 해보니 바로 꺼지네요

**Comment by max-jang** [comment]
> Google 맵으로 좌표 따면, 127.123123, 36.123123 이렇게 6자리로 나오고, 저번주에 되었는데 오늘 해보니 바로 꺼지네요

위경도가 아니고 경위도입니다.
36.123123, 127.123123로 하셔야돼요
https://github.com/SJang1/korea-covid-19-remaining-vaccine-macro/blob/main/docs/coordinates.md

**Comment by AJaaaad** [comment]
경위도로 바꿔 입력하여도, 엔터를 치면 바로 프로그램이 꺼집니다

**Comment by AJaaaad** [comment]
해결했습니다. 예전처럼 하나하나 입력하는것이아닌 경위도 순서로 36.123123, 127.123123 한번에 다 입력해야 하네요~ 
감사합니다

**Comment by AJaaaad** [comment]
단 모두 선착순 마감되었다고 나오네요 ㅠㅠ
